// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.Orgs.Policypacks
{
    [PulumiServiceResourceType("pulumiservice:orgs/policypacks:PolicyPack")]
    public partial class PolicyPack : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Create a PolicyPack resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PolicyPack(string name, PolicyPackArgs? args = null, CustomResourceOptions? options = null)
            : base("pulumiservice:orgs/policypacks:PolicyPack", name, args ?? new PolicyPackArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PolicyPack(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pulumiservice:orgs/policypacks:PolicyPack", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PolicyPack resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PolicyPack Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PolicyPack(name, id, options);
        }
    }

    public sealed class PolicyPackArgs : global::Pulumi.ResourceArgs
    {
        public PolicyPackArgs()
        {
        }
        public static new PolicyPackArgs Empty => new PolicyPackArgs();
    }
}
