// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

import "time"

// An agent slash command.
type AgentSlashCommand struct {
	// The slash command name (e.g. '/fix', '/explain'). Used to invoke the command.
	Name string `json:"name" yaml:"name"`
	// The system prompt text sent to the AI when this command is invoked.
	Prompt string `json:"prompt" yaml:"prompt"`
	// Human-readable description shown to users in the command palette.
	Description string `json:"description" yaml:"description"`
	// Whether this is a built-in system command (true) or user-created (false).
	BuiltIn bool `json:"builtIn" yaml:"builtIn"`
	// When the command was last modified, in ISO 8601 format.
	ModifiedAt time.Time `json:"modifiedAt" yaml:"modifiedAt"`
	// Version tag for optimistic concurrency control.
	Tag string `json:"tag" yaml:"tag"`
}
