// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

import (
	"fmt"
)

// OpType describes the type of operation performed to a resource managed by Pulumi.
// Should generally mirror deploy.StepOp, but we clone it in this package to add
// flexibility in case there is a breaking change in the backend-type.
type AppOpType string

const (
	// OpSame indicates no change was made.
	AppOpTypeOpSame AppOpType = "same"

	// OpCreate indicates a new resource was created.
	AppOpTypeOpCreate AppOpType = "create"

	// OpUpdate indicates an existing resource was updated.
	AppOpTypeOpUpdate AppOpType = "update"

	// OpDelete indicates an existing resource was deleted.
	AppOpTypeOpDelete AppOpType = "delete"

	// OpReplace indicates an existing resource was replaced with a new one.
	AppOpTypeOpReplace AppOpType = "replace"

	// OpCreateReplacement indicates a new resource was created for a replacement.
	AppOpTypeOpCreateReplacement AppOpType = "create-replacement"

	// OpDeleteReplaced indicates an existing resource was deleted after replacement.
	AppOpTypeOpDeleteReplaced AppOpType = "delete-replaced"

	// OpRead indicates reading an existing resource.
	AppOpTypeOpRead AppOpType = "read"

	// OpReadReplacement indicates reading an existing resource for a replacement.
	AppOpTypeOpReadReplacement AppOpType = "read-replacement"

	// OpRefresh indicates refreshing an existing resource.
	AppOpTypeOpRefresh AppOpType = "refresh"

	// OpReadDiscard indicates removing a resource that was read.
	AppOpTypeOpReadDiscard AppOpType = "discard"

	// OpDiscardReplaced indicates discarding a read resource that was replaced.
	AppOpTypeOpDiscardReplaced AppOpType = "discard-replaced"

	// OpRemovePendingReplace indicates removing a pending replace resource.
	AppOpTypeOpRemovePendingReplace AppOpType = "remove-pending-replace"

	// OpImport indicates importing an existing resource.
	AppOpTypeOpImport AppOpType = "import"

	// OpImportReplacement indicates replacement of an existing resource with an imported resource.
	AppOpTypeOpImportReplacement AppOpType = "import-replacement"
)

func (v AppOpType) AllValues() []AppOpType {
	return []AppOpType{
		AppOpTypeOpSame,
		AppOpTypeOpCreate,
		AppOpTypeOpUpdate,
		AppOpTypeOpDelete,
		AppOpTypeOpReplace,
		AppOpTypeOpCreateReplacement,
		AppOpTypeOpDeleteReplaced,
		AppOpTypeOpRead,
		AppOpTypeOpReadReplacement,
		AppOpTypeOpRefresh,
		AppOpTypeOpReadDiscard,
		AppOpTypeOpDiscardReplaced,
		AppOpTypeOpRemovePendingReplace,
		AppOpTypeOpImport,
		AppOpTypeOpImportReplacement,
	}
}

func (v AppOpType) IsValid() bool {
	switch v {
	case AppOpTypeOpSame:
		return true
	case AppOpTypeOpCreate:
		return true
	case AppOpTypeOpUpdate:
		return true
	case AppOpTypeOpDelete:
		return true
	case AppOpTypeOpReplace:
		return true
	case AppOpTypeOpCreateReplacement:
		return true
	case AppOpTypeOpDeleteReplaced:
		return true
	case AppOpTypeOpRead:
		return true
	case AppOpTypeOpReadReplacement:
		return true
	case AppOpTypeOpRefresh:
		return true
	case AppOpTypeOpReadDiscard:
		return true
	case AppOpTypeOpDiscardReplaced:
		return true
	case AppOpTypeOpRemovePendingReplace:
		return true
	case AppOpTypeOpImport:
		return true
	case AppOpTypeOpImportReplacement:
		return true
	}

	return false
}

func (v AppOpType) openapiName() string {
	switch v {
	case AppOpTypeOpSame:
		return "OpSame"
	case AppOpTypeOpCreate:
		return "OpCreate"
	case AppOpTypeOpUpdate:
		return "OpUpdate"
	case AppOpTypeOpDelete:
		return "OpDelete"
	case AppOpTypeOpReplace:
		return "OpReplace"
	case AppOpTypeOpCreateReplacement:
		return "OpCreateReplacement"
	case AppOpTypeOpDeleteReplaced:
		return "OpDeleteReplaced"
	case AppOpTypeOpRead:
		return "OpRead"
	case AppOpTypeOpReadReplacement:
		return "OpReadReplacement"
	case AppOpTypeOpRefresh:
		return "OpRefresh"
	case AppOpTypeOpReadDiscard:
		return "OpReadDiscard"
	case AppOpTypeOpDiscardReplaced:
		return "OpDiscardReplaced"
	case AppOpTypeOpRemovePendingReplace:
		return "OpRemovePendingReplace"
	case AppOpTypeOpImport:
		return "OpImport"
	case AppOpTypeOpImportReplacement:
		return "OpImportReplacement"
	}

	return ""
}
func (v AppOpType) GoString() string {
	if s := v.openapiName(); s != "" {
		return "apitype.AppOpType" + s
	}
	return fmt.Sprintf("apitype.AppOpType(%#v)", string(v))
}
