// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

// AzureDevOpsSettingsRequest describes settings for an Azure DevOps integration.
type AzureDevOpsSettingsRequest struct {
	// Whether PR comments are disabled for this integration
	DisablePRComments bool `json:"disablePRComments,omitzero" yaml:"disablePRComments,omitempty"`
	// Whether Neo AI summaries are disabled for this integration
	DisableNeoSummaries bool `json:"disableNeoSummaries,omitzero" yaml:"disableNeoSummaries,omitempty"`
	// Whether detailed property-level diffs are disabled for PR comments
	DisableDetailedDiff bool `json:"disableDetailedDiff,omitzero" yaml:"disableDetailedDiff,omitempty"`
}
