// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

// Azure provider options
type AzureOptions struct {
	// Azure tenant ID
	TenantID string `json:"tenantId,omitempty" yaml:"tenantId,omitempty"`
	// Azure API name identifying which Azure service to target.
	ApiName AzureApiName `json:"apiName,omitempty" yaml:"apiName,omitempty"`
}
