// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"gopkg.in/yaml.v3"
)

// ChangeRequestCommentedEvent is logged when a user adds a comment.
type ChangeRequestCommentedEvent interface {
	ChangeRequestEvent
	isChangeRequestCommentedEvent()
}

func ChangeRequestCommentedEventChecker[T any]() {
	base := ChangeRequestCommentedEventBuilder{}.Build()
	for _, itf := range base.GetInstancesFromTypeHierarchy() {
		if _, ok := itf.(T); !ok {
			target := reflect.TypeFor[T]()
			msg := fmt.Sprintf("type %T does not implement the %s interface", itf, target)
			panic(msg)
		}
	}
}

func ChangeRequestCommentedEventAsInstance[T ChangeRequestCommentedEvent]() T {
	base := ChangeRequestCommentedEventBuilder{}.Build()
	for _, itf := range base.GetInstancesFromTypeHierarchy() {
		if res, ok := itf.(T); ok {
			return res
		}
	}

	var zero T
	return zero
}

func ChangeRequestCommentedEventAsDiscriminator[T ChangeRequestCommentedEvent]() string {
	var v any
	v = ChangeRequestCommentedEventAsInstance[T]()
	if v2, ok := v.(T); ok {
		disc, _ := v2.GetDiscriminatorValue()
		return disc
	}
	return ""
}

type ChangeRequestCommentedEventBuilder struct {
	ChangeRequestEventBuilder
}

func (b ChangeRequestCommentedEventBuilder) Build() ChangeRequestCommentedEvent {
	return &changeRequestCommentedEventImpl{
		changeRequestEventImpl: changeRequestEventImpl{
			fieldID:              b.ID,
			fieldReplacedBy:      b.ReplacedBy,
			fieldChangeRequestID: b.ChangeRequestID,
			fieldRevisionNumber:  b.RevisionNumber,
			fieldCreatedBy:       b.CreatedBy,
			fieldCreatedAt:       b.CreatedAt,
			fieldComment:         b.Comment,
		},
	}
}

type changeRequestCommentedEventImpl struct {
	changeRequestEventImpl
}

func (m *changeRequestCommentedEventImpl) GetInstancesFromTypeHierarchy() []ChangeRequestEvent {
	return []ChangeRequestEvent{
		&changeRequestCommentedEventImpl{},
	}
}

func (m *changeRequestCommentedEventImpl) GetDiscriminatorValue() (string, error) {
	return "commented", nil
}

func (m *changeRequestCommentedEventImpl) isChangeRequestCommentedEvent() {} // interface type checking

func (m *changeRequestCommentedEventImpl) isChangeRequestEvent() {} // interface type checking

func (m *changeRequestCommentedEventImpl) MarshalJSON() ([]byte, error) {
	type marshaller struct {
		InternalDiscriminator string    `json:"eventType,omitempty"`
		FieldID               string    `json:"id"`
		FieldReplacedBy       *string   `json:"replacedBy,omitempty"`
		FieldChangeRequestID  string    `json:"changeRequestId"`
		FieldRevisionNumber   *int64    `json:"revisionNumber"`
		FieldCreatedBy        UserInfo  `json:"createdBy"`
		FieldCreatedAt        time.Time `json:"createdAt"`
		FieldComment          *string   `json:"comment,omitempty"`
	}

	var v marshaller
	v.InternalDiscriminator = "commented"
	v.FieldID = m.fieldID
	v.FieldReplacedBy = m.fieldReplacedBy
	v.FieldChangeRequestID = m.fieldChangeRequestID
	v.FieldRevisionNumber = m.fieldRevisionNumber
	v.FieldCreatedBy = m.fieldCreatedBy
	v.FieldCreatedAt = m.fieldCreatedAt
	v.FieldComment = m.fieldComment
	return json.Marshal(v)
}

func (m *changeRequestCommentedEventImpl) UnmarshalJSON(bytes []byte) error {
	type decoder struct {
		FieldID              string    `json:"id"`
		FieldReplacedBy      *string   `json:"replacedBy,omitempty"`
		FieldChangeRequestID string    `json:"changeRequestId"`
		FieldRevisionNumber  *int64    `json:"revisionNumber"`
		FieldCreatedBy       UserInfo  `json:"createdBy"`
		FieldCreatedAt       time.Time `json:"createdAt"`
		FieldComment         *string   `json:"comment,omitempty"`
	}

	var v decoder
	var err error
	if err = json.Unmarshal(bytes, &v); err != nil {
		return err
	}
	m.fieldID = v.FieldID
	m.fieldReplacedBy = v.FieldReplacedBy
	m.fieldChangeRequestID = v.FieldChangeRequestID
	m.fieldRevisionNumber = v.FieldRevisionNumber
	m.fieldCreatedBy = v.FieldCreatedBy
	m.fieldCreatedAt = v.FieldCreatedAt
	m.fieldComment = v.FieldComment
	return nil
}

func (m changeRequestCommentedEventImpl) MarshalYAML() (any, error) {
	type marshaller struct {
		InternalDiscriminator string    `yaml:"eventType"`
		FieldID               string    `yaml:"id,omitempty"`
		FieldReplacedBy       *string   `yaml:"replacedBy,omitempty"`
		FieldChangeRequestID  string    `yaml:"changeRequestId,omitempty"`
		FieldRevisionNumber   *int64    `yaml:"revisionNumber,omitempty"`
		FieldCreatedBy        UserInfo  `yaml:"createdBy,omitempty"`
		FieldCreatedAt        time.Time `yaml:"createdAt,omitempty"`
		FieldComment          *string   `yaml:"comment,omitempty"`
	}

	var v marshaller
	v.InternalDiscriminator = "commented"
	v.FieldID = m.fieldID
	v.FieldReplacedBy = m.fieldReplacedBy
	v.FieldChangeRequestID = m.fieldChangeRequestID
	v.FieldRevisionNumber = m.fieldRevisionNumber
	v.FieldCreatedBy = m.fieldCreatedBy
	v.FieldCreatedAt = m.fieldCreatedAt
	v.FieldComment = m.fieldComment
	return &v, nil
}

func (m *changeRequestCommentedEventImpl) UnmarshalYAML(value *yaml.Node) error {
	type decoder struct {
		FieldID              string    `yaml:"id,omitempty"`
		FieldReplacedBy      *string   `yaml:"replacedBy,omitempty"`
		FieldChangeRequestID string    `yaml:"changeRequestId,omitempty"`
		FieldRevisionNumber  *int64    `yaml:"revisionNumber,omitempty"`
		FieldCreatedBy       UserInfo  `yaml:"createdBy,omitempty"`
		FieldCreatedAt       time.Time `yaml:"createdAt,omitempty"`
		FieldComment         *string   `yaml:"comment,omitempty"`
	}

	var v decoder
	var err error
	if err = value.Decode(&v); err != nil {
		return err
	}
	m.fieldID = v.FieldID
	m.fieldReplacedBy = v.FieldReplacedBy
	m.fieldChangeRequestID = v.FieldChangeRequestID
	m.fieldRevisionNumber = v.FieldRevisionNumber
	m.fieldCreatedBy = v.FieldCreatedBy
	m.fieldCreatedAt = v.FieldCreatedAt
	m.fieldComment = v.FieldComment
	return nil
}
