// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

// README content for a registry package, structured as an ordered list of content nodes. When a language or OS filter is applied, language-
// and OS-specific content is collapsed to the requested value.
type GetPackageReadmeResponse struct {
	// The resolved semantic version of the package.
	Version string `json:"version" yaml:"version"`
	// The language the content was filtered for, if a language filter was applied.
	Language *string `json:"language,omitempty" yaml:"language,omitempty"`
	// The operating system the content was filtered for, if an OS filter was applied.
	Os *string `json:"os,omitempty" yaml:"os,omitempty"`
	// Path to the package navigation endpoint for this version.
	NavUrl string `json:"navUrl" yaml:"navUrl"`
	// Ordered list of content nodes composing the README document.
	Content []RegistryContentNode `json:"content" yaml:"content"`
}
