// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

import (
	ext1 "github.com/pulumi/pulumi-pulumiservice/provider/pkg/apitype/jsonvalue"
)

// Request body for configuring git authentication options.
type GitAuthConfigRequest struct {
	// Personal access token for git authentication
	PersonalAccessToken ext1.Value[SecretValue] `json:"accessToken,omitempty" yaml:"accessToken,omitempty"`
	// SSH authentication configuration
	SSHAuth ext1.Value[SSHAuthRequest] `json:"sshAuth,omitempty" yaml:"sshAuth,omitempty"`
	// Basic authentication configuration
	BasicAuth ext1.Value[BasicAuthRequest] `json:"basicAuth,omitempty" yaml:"basicAuth,omitempty"`
}
