// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

// PolicyIssueFiltersRequest is a request to retrieve available filter values for policy issues.
type PolicyIssueFiltersRequest struct {
	// Optional filter model to apply when getting available filter values. Same format as used in policy issues list.
	FilterModel *AngularGridAdvancedFilterModel `json:"filterModel,omitempty" yaml:"filterModel,omitempty"`
	// Field name
	Field string `json:"field" yaml:"field"`
}
