// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

// A service member is either a direct user or a indirect user representation
// that allows them to access and mutate a service.
type ServiceMember struct {
	// the type of the member (e.g. team / user)
	Type string `json:"type" yaml:"type"`
	// the login name of the member within Pulumi
	Name string `json:"name" yaml:"name"`
	// an optional avatar URL for the member
	AvatarURL string `json:"avatarUrl" yaml:"avatarUrl"`
}
