// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

// UnitRateGraduatedV0 describes the rate for each unit of a Pulumi Subscription. The specific value is intended to
// be opaque, and only obtained via parsing.
// This rate was introduced as our first Growth pricing plans, representing a simplified version of a graduated
// pricing plan that merges together two tiers. It can later be extended to handle other types of straightforward
// pricing plans, e.g. tiered pricing or flat-rate plans. For now only supports our per-Pulumi credit plans
// that have a single overage rate.
type UnitRateGraduatedV0 struct {
	// UpfrontCost is the up-front charge the customer will have paid to have an active subscription.
	// For Team Growth this is $0, since there is no credit pre-payment and has free-tier. But for
	// Enterprise Growth, it is usually (Rate * CreditsIncluded).
	//
	// Value is in USD cents.
	UpfrontCost int64 `json:"upfrontCost" yaml:"upfrontCost"`
	// IncludedCredits is the number of resource-hours included in the subscription, e.g. the
	// pre-paid credits or those in the "free tier".
	// Keep the JSON tag as "creditsIncluded" to maintain compatibility with the frontend
	// until we consolidate product.UnitRateGraduatedV0 and apitype.UnitRateGraduatedV1.
	IncludedCredits int64 `json:"creditsIncluded" yaml:"creditsIncluded"`
	// PerUnitCost is a user-facing string describing the cost-per unit with the currency symbol.
	// e.g. "$0.0005".
	// Keep the JSON tag as "costPerResource" to maintain compatibility with the frontend
	// until we consolidate product.UnitRateGraduatedV0 and apitype.UnitRateGraduatedV1.
	PerUnitCost string `json:"costPerResource" yaml:"costPerResource"`
}
