// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

// UpdateSummary contains a subset of the update data found in apitype.UpdateInfo.
type UpdateSummary struct {
	// The result of the update.
	Result AppUpdateResult `json:"result" yaml:"result"`
	// The start time of the update as a Unix timestamp.
	StartTime int64 `json:"startTime" yaml:"startTime"`
	// The end time of the update as a Unix timestamp.
	EndTime int64 `json:"endTime" yaml:"endTime"`
	// ResourceCount is the current resource count for the update. Note that it
	// doesn't reflect the Stack's current resource count, only that particular
	// update. (So the UpdateSummary for the same Stack will be different.)
	ResourceCount int64 `json:"resourceCount" yaml:"resourceCount"`
}
