// Copyright 2026, Pulumi Corporation.  All rights reserved.

// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// RUN 'make openapi_all' TO REFRESH.

//nolint:revive
package apitype

// Request to update a task.
type UpdateTaskRequest struct {
	// A new display name for the task. Null means no change. Must be between 1 and 255 characters after trimming whitespace.
	Name *string `json:"name,omitempty" yaml:"name,omitempty"`
	// Whether to share the task with other org members. Null means no change.
	IsShared *bool `json:"isShared,omitzero" yaml:"isShared,omitempty"`
	// Approval mode for this task. Null means no change. Valid values: 'manual', 'auto', 'balanced'.
	ApprovalMode *NeoApprovalMode `json:"approvalMode,omitempty" yaml:"approvalMode,omitempty"`
	// The permission scope for the task. Null means no change.
	PermissionMode *NeoPermissionMode `json:"permissionMode,omitempty" yaml:"permissionMode,omitempty"`
}
