// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v2

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-pulumiservice/sdk/go/pulumiservice/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a new Pulumi ESC (Environments, Secrets, and Configuration) environment within the specified organization. The request body must include the project name and the environment name. Environment names must be unique within a project and may only contain alphanumeric characters, hyphens, underscores, and periods. The newly created environment starts with an empty YAML definition that can be updated via the UpdateEnvironment endpoint.
type Environment_preview_environments struct {
	pulumi.CustomResourceState

	// The environment name
	EnvName pulumi.StringOutput `pulumi:"envName"`
	// The organization name
	OrgName pulumi.StringOutput `pulumi:"orgName"`
}

// NewEnvironment_preview_environments registers a new resource with the given unique name, arguments, and options.
func NewEnvironment_preview_environments(ctx *pulumi.Context,
	name string, args *Environment_preview_environmentsArgs, opts ...pulumi.ResourceOption) (*Environment_preview_environments, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EnvName == nil {
		return nil, errors.New("invalid value for required argument 'EnvName'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.OrgName == nil {
		return nil, errors.New("invalid value for required argument 'OrgName'")
	}
	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"envName",
		"orgName",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Environment_preview_environments
	err := ctx.RegisterResource("pulumiservice:v2:Environment_preview_environments", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnvironment_preview_environments gets an existing Environment_preview_environments resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnvironment_preview_environments(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *Environment_preview_environmentsState, opts ...pulumi.ResourceOption) (*Environment_preview_environments, error) {
	var resource Environment_preview_environments
	err := ctx.ReadResource("pulumiservice:v2:Environment_preview_environments", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Environment_preview_environments resources.
type environment_preview_environmentsState struct {
}

type Environment_preview_environmentsState struct {
}

func (Environment_preview_environmentsState) ElementType() reflect.Type {
	return reflect.TypeOf((*environment_preview_environmentsState)(nil)).Elem()
}

type environment_preview_environmentsArgs struct {
	// The environment name
	EnvName string `pulumi:"envName"`
	// The name of the environment.
	Name string `pulumi:"name"`
	// The organization name
	OrgName string `pulumi:"orgName"`
	// The project name for the environment.
	Project string `pulumi:"project"`
}

// The set of arguments for constructing a Environment_preview_environments resource.
type Environment_preview_environmentsArgs struct {
	// The environment name
	EnvName pulumi.StringInput
	// The name of the environment.
	Name pulumi.StringInput
	// The organization name
	OrgName pulumi.StringInput
	// The project name for the environment.
	Project pulumi.StringInput
}

func (Environment_preview_environmentsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*environment_preview_environmentsArgs)(nil)).Elem()
}

type Environment_preview_environmentsInput interface {
	pulumi.Input

	ToEnvironment_preview_environmentsOutput() Environment_preview_environmentsOutput
	ToEnvironment_preview_environmentsOutputWithContext(ctx context.Context) Environment_preview_environmentsOutput
}

func (*Environment_preview_environments) ElementType() reflect.Type {
	return reflect.TypeOf((**Environment_preview_environments)(nil)).Elem()
}

func (i *Environment_preview_environments) ToEnvironment_preview_environmentsOutput() Environment_preview_environmentsOutput {
	return i.ToEnvironment_preview_environmentsOutputWithContext(context.Background())
}

func (i *Environment_preview_environments) ToEnvironment_preview_environmentsOutputWithContext(ctx context.Context) Environment_preview_environmentsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Environment_preview_environmentsOutput)
}

// Environment_preview_environmentsArrayInput is an input type that accepts Environment_preview_environmentsArray and Environment_preview_environmentsArrayOutput values.
// You can construct a concrete instance of `Environment_preview_environmentsArrayInput` via:
//
//	Environment_preview_environmentsArray{ Environment_preview_environmentsArgs{...} }
type Environment_preview_environmentsArrayInput interface {
	pulumi.Input

	ToEnvironment_preview_environmentsArrayOutput() Environment_preview_environmentsArrayOutput
	ToEnvironment_preview_environmentsArrayOutputWithContext(context.Context) Environment_preview_environmentsArrayOutput
}

type Environment_preview_environmentsArray []Environment_preview_environmentsInput

func (Environment_preview_environmentsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Environment_preview_environments)(nil)).Elem()
}

func (i Environment_preview_environmentsArray) ToEnvironment_preview_environmentsArrayOutput() Environment_preview_environmentsArrayOutput {
	return i.ToEnvironment_preview_environmentsArrayOutputWithContext(context.Background())
}

func (i Environment_preview_environmentsArray) ToEnvironment_preview_environmentsArrayOutputWithContext(ctx context.Context) Environment_preview_environmentsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Environment_preview_environmentsArrayOutput)
}

// Environment_preview_environmentsMapInput is an input type that accepts Environment_preview_environmentsMap and Environment_preview_environmentsMapOutput values.
// You can construct a concrete instance of `Environment_preview_environmentsMapInput` via:
//
//	Environment_preview_environmentsMap{ "key": Environment_preview_environmentsArgs{...} }
type Environment_preview_environmentsMapInput interface {
	pulumi.Input

	ToEnvironment_preview_environmentsMapOutput() Environment_preview_environmentsMapOutput
	ToEnvironment_preview_environmentsMapOutputWithContext(context.Context) Environment_preview_environmentsMapOutput
}

type Environment_preview_environmentsMap map[string]Environment_preview_environmentsInput

func (Environment_preview_environmentsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Environment_preview_environments)(nil)).Elem()
}

func (i Environment_preview_environmentsMap) ToEnvironment_preview_environmentsMapOutput() Environment_preview_environmentsMapOutput {
	return i.ToEnvironment_preview_environmentsMapOutputWithContext(context.Background())
}

func (i Environment_preview_environmentsMap) ToEnvironment_preview_environmentsMapOutputWithContext(ctx context.Context) Environment_preview_environmentsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Environment_preview_environmentsMapOutput)
}

type Environment_preview_environmentsOutput struct{ *pulumi.OutputState }

func (Environment_preview_environmentsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Environment_preview_environments)(nil)).Elem()
}

func (o Environment_preview_environmentsOutput) ToEnvironment_preview_environmentsOutput() Environment_preview_environmentsOutput {
	return o
}

func (o Environment_preview_environmentsOutput) ToEnvironment_preview_environmentsOutputWithContext(ctx context.Context) Environment_preview_environmentsOutput {
	return o
}

// The environment name
func (o Environment_preview_environmentsOutput) EnvName() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment_preview_environments) pulumi.StringOutput { return v.EnvName }).(pulumi.StringOutput)
}

// The organization name
func (o Environment_preview_environmentsOutput) OrgName() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment_preview_environments) pulumi.StringOutput { return v.OrgName }).(pulumi.StringOutput)
}

type Environment_preview_environmentsArrayOutput struct{ *pulumi.OutputState }

func (Environment_preview_environmentsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Environment_preview_environments)(nil)).Elem()
}

func (o Environment_preview_environmentsArrayOutput) ToEnvironment_preview_environmentsArrayOutput() Environment_preview_environmentsArrayOutput {
	return o
}

func (o Environment_preview_environmentsArrayOutput) ToEnvironment_preview_environmentsArrayOutputWithContext(ctx context.Context) Environment_preview_environmentsArrayOutput {
	return o
}

func (o Environment_preview_environmentsArrayOutput) Index(i pulumi.IntInput) Environment_preview_environmentsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Environment_preview_environments {
		return vs[0].([]*Environment_preview_environments)[vs[1].(int)]
	}).(Environment_preview_environmentsOutput)
}

type Environment_preview_environmentsMapOutput struct{ *pulumi.OutputState }

func (Environment_preview_environmentsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Environment_preview_environments)(nil)).Elem()
}

func (o Environment_preview_environmentsMapOutput) ToEnvironment_preview_environmentsMapOutput() Environment_preview_environmentsMapOutput {
	return o
}

func (o Environment_preview_environmentsMapOutput) ToEnvironment_preview_environmentsMapOutputWithContext(ctx context.Context) Environment_preview_environmentsMapOutput {
	return o
}

func (o Environment_preview_environmentsMapOutput) MapIndex(k pulumi.StringInput) Environment_preview_environmentsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Environment_preview_environments {
		return vs[0].(map[string]*Environment_preview_environments)[vs[1].(string)]
	}).(Environment_preview_environmentsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*Environment_preview_environmentsInput)(nil)).Elem(), &Environment_preview_environments{})
	pulumi.RegisterInputType(reflect.TypeOf((*Environment_preview_environmentsArrayInput)(nil)).Elem(), Environment_preview_environmentsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*Environment_preview_environmentsMapInput)(nil)).Elem(), Environment_preview_environmentsMap{})
	pulumi.RegisterOutputType(Environment_preview_environmentsOutput{})
	pulumi.RegisterOutputType(Environment_preview_environmentsArrayOutput{})
	pulumi.RegisterOutputType(Environment_preview_environmentsMapOutput{})
}
