// Code-generated goconst constant extraction. package resources
package resources

const (
	gcInputs           = "__inputs"
	gcDescription      = "description"
	gcValue            = "value"
	gcAgentPoolID      = "agentPoolID"
	gcName             = "name"
	gcOrganizationName = "organizationName"
	gcTokenValue       = "tokenValue"
	gcEnvironment      = "environment"
	gcTimestamp        = "timestamp"
	gcOrganization     = "organization"
	gcProject          = "project"
	gcStack            = "stack"
	gcYaml             = "yaml"
	gcAWS              = "aws"
	gcRegions          = "regions"
	gcTeam             = "team"
	gcAdmin            = "admin"
	gcPermissions      = "permissions"
	gcGlobal           = "global"
	gcEntityType       = "entityType"
	gcMode             = "mode"
	gcStacks           = "stacks"
	gcAccounts         = "accounts"
	gcPolicyPacks      = "policyPacks"
	gcDisplayName      = "displayName"
	gcVersionTag       = "versionTag"
	gcAudit            = "audit"
	gcPreventative     = "preventative"
	gcParentChild      = "parent/child"
	gcObject           = "object"
	gcType             = "type"
	gcSourceName       = "sourceName"
	gcSourceURL        = "sourceURL"
	gcProjectName      = "projectName"
	gcParent           = "parent"
	gcRequired         = "required"
	gcTeamName         = "teamName"
)
