// Code-generated goconst constant extraction. package resources
package resources

const (
	gcTokSecretValue      = "tok-secret-value"
	gcMyOrg               = "my-org"
	gcMyProject           = "my-project"
	gcOrg                 = "org"
	gcEnv                 = "env"
	gcTestOrgAccount      = "test-org/test-account"
	gcTestOrg             = "test-org"
	gcTestAccount         = "test-account"
	gcTestEnv             = "test-env"
	gcTestAccountID       = "test-account-id"
	gcUSWest2             = "us-west-2"
	gcAccountID123        = "account-id-123"
	gcUpdatedEnv          = "updated-env"
	gcOldEnv              = "old-env"
	gcStaging             = "staging"
	gcAdminCap            = "Admin"
	gcAdminFGA            = "admin-fga"
	gcAcmeAlice           = "acme/alice"
	gcAlice               = "alice"
	gcBob                 = "bob"
	gcAcme                = "acme"
	gcTypeMeta            = "__type"
	gcRoleID              = "role-123"
	gcReadOnly            = "read-only"
	gcTestPolicyGroup     = "test-policy-group"
	gcOther               = "other"
	gcProject1            = "project-1"
	gcVersion100          = "1.0.0"
	gcNoSecrets           = "no-secrets"
	gcMandatory           = "mandatory"
	gcThreshold           = "threshold"
	gcGuard               = "guard"
	gcRule                = "rule"
	gcGuardCap            = "Guard"
	gcAcmeGuard100        = "acme/guard/1.0.0"
	gcMyTag               = "myTag"
	gcMyValue             = "myValue"
	gcABC                 = "abc"
	gcMember1             = "member1"
	gcMember2             = "member2"
	gcTag3                = "tag3"
	gcTag1                = "tag1"
	gcTag4                = "tag4"
	gcOrgProjectStackTags = "org/project/stack/tags"
	gcDevops              = "devops"
	gcProduction          = "production"
	gcStack1              = "stack-1"
	gcPolicyPack1         = "policy-pack-1"
	gcTag2                = "tag2"
	gcV2New               = "v2-new"
)
