// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService
{
    /// <summary>
    /// An approval rule for environment deployments.
    /// </summary>
    [PulumiServiceResourceType("pulumiservice:index:ApprovalRule")]
    public partial class ApprovalRule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The approval rule configuration.
        /// </summary>
        [Output("approvalRuleConfig")]
        public Output<Outputs.ApprovalRuleConfig> ApprovalRuleConfig { get; private set; } = null!;

        /// <summary>
        /// Whether the approval rule is enabled.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// The environment this rule applies to.
        /// </summary>
        [Output("environmentIdentifier")]
        public Output<Outputs.EnvironmentIdentifier> EnvironmentIdentifier { get; private set; } = null!;

        /// <summary>
        /// Name of the approval rule.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The type of action this rule applies to.
        /// </summary>
        [Output("targetActionTypes")]
        public Output<ImmutableArray<Pulumi.PulumiService.TargetActionType>> TargetActionTypes { get; private set; } = null!;


        /// <summary>
        /// Create a ApprovalRule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ApprovalRule(string name, ApprovalRuleArgs args, CustomResourceOptions? options = null)
            : base("pulumiservice:index:ApprovalRule", name, args ?? new ApprovalRuleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ApprovalRule(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pulumiservice:index:ApprovalRule", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ApprovalRule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ApprovalRule Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ApprovalRule(name, id, options);
        }
    }

    public sealed class ApprovalRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The approval rule configuration.
        /// </summary>
        [Input("approvalRuleConfig", required: true)]
        public Input<Inputs.ApprovalRuleConfigArgs> ApprovalRuleConfig { get; set; } = null!;

        /// <summary>
        /// Whether the approval rule is enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// The environment this rule applies to.
        /// </summary>
        [Input("environmentIdentifier", required: true)]
        public Input<Inputs.EnvironmentIdentifierArgs> EnvironmentIdentifier { get; set; } = null!;

        /// <summary>
        /// The name of the approval rule.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("targetActionTypes", required: true)]
        private InputList<Pulumi.PulumiService.TargetActionType>? _targetActionTypes;

        /// <summary>
        /// The type of action this rule applies to.
        /// </summary>
        public InputList<Pulumi.PulumiService.TargetActionType> TargetActionTypes
        {
            get => _targetActionTypes ?? (_targetActionTypes = new InputList<Pulumi.PulumiService.TargetActionType>());
            set => _targetActionTypes = value;
        }

        public ApprovalRuleArgs()
        {
        }
        public static new ApprovalRuleArgs Empty => new ApprovalRuleArgs();
    }
}
