// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.Api.Outputs
{

    [OutputType]
    public sealed class ApprovalRuleEligibilityOutputTeam
    {
        /// <summary>
        /// Display name
        /// </summary>
        public readonly string DisplayName;
        /// <summary>
        /// Expected value is 'team_member'.
        /// </summary>
        public readonly string EligibilityType;
        /// <summary>
        /// Team name
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ApprovalRuleEligibilityOutputTeam(
            string displayName,

            string eligibilityType,

            string name)
        {
            DisplayName = displayName;
            EligibilityType = eligibilityType;
            Name = name;
        }
    }
}
