// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.Api.Outputs
{

    [OutputType]
    public sealed class PermissionExpressionHasTag
    {
        /// <summary>
        /// Expected value is 'PermissionExpressionHasTag'.
        /// </summary>
        public readonly string __type;
        /// <summary>
        /// The context expression to check for the tag.
        /// </summary>
        public readonly Outputs.PermissionContextExpression? Context;
        /// <summary>
        /// The tag key to check for.
        /// </summary>
        public readonly string? Key;
        /// <summary>
        /// The operand of the unary boolean expression.
        /// </summary>
        public readonly Outputs.PermissionBooleanExpression? Node;

        [OutputConstructor]
        private PermissionExpressionHasTag(
            string __type,

            Outputs.PermissionContextExpression? context,

            string? key,

            Outputs.PermissionBooleanExpression? node)
        {
            this.__type = __type;
            Context = context;
            Key = key;
            Node = node;
        }
    }
}
