// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.v2;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class DefaultOrganizationArgs extends com.pulumi.resources.ResourceArgs {

    public static final DefaultOrganizationArgs Empty = new DefaultOrganizationArgs();

    /**
     * The organization name
     * 
     */
    @Import(name="orgName", required=true)
    private Output<String> orgName;

    /**
     * @return The organization name
     * 
     */
    public Output<String> orgName() {
        return this.orgName;
    }

    private DefaultOrganizationArgs() {}

    private DefaultOrganizationArgs(DefaultOrganizationArgs $) {
        this.orgName = $.orgName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DefaultOrganizationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DefaultOrganizationArgs $;

        public Builder() {
            $ = new DefaultOrganizationArgs();
        }

        public Builder(DefaultOrganizationArgs defaults) {
            $ = new DefaultOrganizationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param orgName The organization name
         * 
         * @return builder
         * 
         */
        public Builder orgName(Output<String> orgName) {
            $.orgName = orgName;
            return this;
        }

        /**
         * @param orgName The organization name
         * 
         * @return builder
         * 
         */
        public Builder orgName(String orgName) {
            return orgName(Output.of(orgName));
        }

        public DefaultOrganizationArgs build() {
            if ($.orgName == null) {
                throw new MissingRequiredPropertyException("DefaultOrganizationArgs", "orgName");
            }
            return $;
        }
    }

}
