// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.v2;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class StackConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final StackConfigArgs Empty = new StackConfigArgs();

    /**
     * The KMS-encrypted ciphertext for the data key used for secrets encryption. Only used for cloud-based secrets providers.
     * 
     */
    @Import(name="encryptedKey")
    private @Nullable Output<String> encryptedKey;

    /**
     * @return The KMS-encrypted ciphertext for the data key used for secrets encryption. Only used for cloud-based secrets providers.
     * 
     */
    public Optional<Output<String>> encryptedKey() {
        return Optional.ofNullable(this.encryptedKey);
    }

    /**
     * The stack&#39;s base64-encoded encryption salt. Only used for passphrase-based secrets providers.
     * 
     */
    @Import(name="encryptionSalt")
    private @Nullable Output<String> encryptionSalt;

    /**
     * @return The stack&#39;s base64-encoded encryption salt. Only used for passphrase-based secrets providers.
     * 
     */
    public Optional<Output<String>> encryptionSalt() {
        return Optional.ofNullable(this.encryptionSalt);
    }

    /**
     * Reference to ESC environment to use as stack configuration.
     * 
     */
    @Import(name="environment", required=true)
    private Output<String> environment;

    /**
     * @return Reference to ESC environment to use as stack configuration.
     * 
     */
    public Output<String> environment() {
        return this.environment;
    }

    /**
     * The organization name
     * 
     */
    @Import(name="orgName", required=true)
    private Output<String> orgName;

    /**
     * @return The organization name
     * 
     */
    public Output<String> orgName() {
        return this.orgName;
    }

    /**
     * The project name
     * 
     */
    @Import(name="projectName", required=true)
    private Output<String> projectName;

    /**
     * @return The project name
     * 
     */
    public Output<String> projectName() {
        return this.projectName;
    }

    /**
     * The stack&#39;s secrets provider.
     * 
     */
    @Import(name="secretsProvider")
    private @Nullable Output<String> secretsProvider;

    /**
     * @return The stack&#39;s secrets provider.
     * 
     */
    public Optional<Output<String>> secretsProvider() {
        return Optional.ofNullable(this.secretsProvider);
    }

    /**
     * The stack name
     * 
     */
    @Import(name="stackName", required=true)
    private Output<String> stackName;

    /**
     * @return The stack name
     * 
     */
    public Output<String> stackName() {
        return this.stackName;
    }

    private StackConfigArgs() {}

    private StackConfigArgs(StackConfigArgs $) {
        this.encryptedKey = $.encryptedKey;
        this.encryptionSalt = $.encryptionSalt;
        this.environment = $.environment;
        this.orgName = $.orgName;
        this.projectName = $.projectName;
        this.secretsProvider = $.secretsProvider;
        this.stackName = $.stackName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(StackConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private StackConfigArgs $;

        public Builder() {
            $ = new StackConfigArgs();
        }

        public Builder(StackConfigArgs defaults) {
            $ = new StackConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param encryptedKey The KMS-encrypted ciphertext for the data key used for secrets encryption. Only used for cloud-based secrets providers.
         * 
         * @return builder
         * 
         */
        public Builder encryptedKey(@Nullable Output<String> encryptedKey) {
            $.encryptedKey = encryptedKey;
            return this;
        }

        /**
         * @param encryptedKey The KMS-encrypted ciphertext for the data key used for secrets encryption. Only used for cloud-based secrets providers.
         * 
         * @return builder
         * 
         */
        public Builder encryptedKey(String encryptedKey) {
            return encryptedKey(Output.of(encryptedKey));
        }

        /**
         * @param encryptionSalt The stack&#39;s base64-encoded encryption salt. Only used for passphrase-based secrets providers.
         * 
         * @return builder
         * 
         */
        public Builder encryptionSalt(@Nullable Output<String> encryptionSalt) {
            $.encryptionSalt = encryptionSalt;
            return this;
        }

        /**
         * @param encryptionSalt The stack&#39;s base64-encoded encryption salt. Only used for passphrase-based secrets providers.
         * 
         * @return builder
         * 
         */
        public Builder encryptionSalt(String encryptionSalt) {
            return encryptionSalt(Output.of(encryptionSalt));
        }

        /**
         * @param environment Reference to ESC environment to use as stack configuration.
         * 
         * @return builder
         * 
         */
        public Builder environment(Output<String> environment) {
            $.environment = environment;
            return this;
        }

        /**
         * @param environment Reference to ESC environment to use as stack configuration.
         * 
         * @return builder
         * 
         */
        public Builder environment(String environment) {
            return environment(Output.of(environment));
        }

        /**
         * @param orgName The organization name
         * 
         * @return builder
         * 
         */
        public Builder orgName(Output<String> orgName) {
            $.orgName = orgName;
            return this;
        }

        /**
         * @param orgName The organization name
         * 
         * @return builder
         * 
         */
        public Builder orgName(String orgName) {
            return orgName(Output.of(orgName));
        }

        /**
         * @param projectName The project name
         * 
         * @return builder
         * 
         */
        public Builder projectName(Output<String> projectName) {
            $.projectName = projectName;
            return this;
        }

        /**
         * @param projectName The project name
         * 
         * @return builder
         * 
         */
        public Builder projectName(String projectName) {
            return projectName(Output.of(projectName));
        }

        /**
         * @param secretsProvider The stack&#39;s secrets provider.
         * 
         * @return builder
         * 
         */
        public Builder secretsProvider(@Nullable Output<String> secretsProvider) {
            $.secretsProvider = secretsProvider;
            return this;
        }

        /**
         * @param secretsProvider The stack&#39;s secrets provider.
         * 
         * @return builder
         * 
         */
        public Builder secretsProvider(String secretsProvider) {
            return secretsProvider(Output.of(secretsProvider));
        }

        /**
         * @param stackName The stack name
         * 
         * @return builder
         * 
         */
        public Builder stackName(Output<String> stackName) {
            $.stackName = stackName;
            return this;
        }

        /**
         * @param stackName The stack name
         * 
         * @return builder
         * 
         */
        public Builder stackName(String stackName) {
            return stackName(Output.of(stackName));
        }

        public StackConfigArgs build() {
            if ($.environment == null) {
                throw new MissingRequiredPropertyException("StackConfigArgs", "environment");
            }
            if ($.orgName == null) {
                throw new MissingRequiredPropertyException("StackConfigArgs", "orgName");
            }
            if ($.projectName == null) {
                throw new MissingRequiredPropertyException("StackConfigArgs", "projectName");
            }
            if ($.stackName == null) {
                throw new MissingRequiredPropertyException("StackConfigArgs", "stackName");
            }
            return $;
        }
    }

}
