// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.v2;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class Webhook_esc_environmentsArgs extends com.pulumi.resources.ResourceArgs {

    public static final Webhook_esc_environmentsArgs Empty = new Webhook_esc_environmentsArgs();

    /**
     * Whether the webhook is active and will receive deliveries.
     * 
     */
    @Import(name="active", required=true)
    private Output<Boolean> active;

    /**
     * @return Whether the webhook is active and will receive deliveries.
     * 
     */
    public Output<Boolean> active() {
        return this.active;
    }

    /**
     * The human-readable display name shown in the UI.
     * 
     */
    @Import(name="displayName", required=true)
    private Output<String> displayName;

    /**
     * @return The human-readable display name shown in the UI.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }

    /**
     * The environment name. Set when the webhook is scoped to a specific environment.
     * 
     */
    @Import(name="envName", required=true)
    private Output<String> envName;

    /**
     * @return The environment name. Set when the webhook is scoped to a specific environment.
     * 
     */
    public Output<String> envName() {
        return this.envName;
    }

    /**
     * Specific event types this webhook subscribes to. If empty, all events are delivered.
     * 
     */
    @Import(name="filters")
    private @Nullable Output<List<String>> filters;

    /**
     * @return Specific event types this webhook subscribes to. If empty, all events are delivered.
     * 
     */
    public Optional<Output<List<String>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    /**
     * The format of the webhook payload (e.g., &#39;raw&#39;, &#39;slack&#39;, &#39;ms_teams&#39;).
     * 
     */
    @Import(name="format")
    private @Nullable Output<String> format;

    /**
     * @return The format of the webhook payload (e.g., &#39;raw&#39;, &#39;slack&#39;, &#39;ms_teams&#39;).
     * 
     */
    public Optional<Output<String>> format() {
        return Optional.ofNullable(this.format);
    }

    /**
     * Event groups this webhook subscribes to (e.g., &#39;stacks&#39;, &#39;deployments&#39;).
     * 
     */
    @Import(name="groups")
    private @Nullable Output<List<String>> groups;

    /**
     * @return Event groups this webhook subscribes to (e.g., &#39;stacks&#39;, &#39;deployments&#39;).
     * 
     */
    public Optional<Output<List<String>>> groups() {
        return Optional.ofNullable(this.groups);
    }

    /**
     * The unique identifier name for the webhook within its scope.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The unique identifier name for the webhook within its scope.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * The organization that owns this webhook.
     * 
     */
    @Import(name="organizationName", required=true)
    private Output<String> organizationName;

    /**
     * @return The organization that owns this webhook.
     * 
     */
    public Output<String> organizationName() {
        return this.organizationName;
    }

    /**
     * The URL to which webhook payloads are delivered.
     * 
     */
    @Import(name="payloadUrl", required=true)
    private Output<String> payloadUrl;

    /**
     * @return The URL to which webhook payloads are delivered.
     * 
     */
    public Output<String> payloadUrl() {
        return this.payloadUrl;
    }

    /**
     * The project name. Set when the webhook is scoped to a specific stack.
     * 
     */
    @Import(name="projectName", required=true)
    private Output<String> projectName;

    /**
     * @return The project name. Set when the webhook is scoped to a specific stack.
     * 
     */
    public Output<String> projectName() {
        return this.projectName;
    }

    /**
     * Secret will be omitted when returned from the service.
     * 
     */
    @Import(name="secret")
    private @Nullable Output<String> secret;

    /**
     * @return Secret will be omitted when returned from the service.
     * 
     */
    public Optional<Output<String>> secret() {
        return Optional.ofNullable(this.secret);
    }

    /**
     * The stack name. Set when the webhook is scoped to a specific stack.
     * 
     */
    @Import(name="stackName")
    private @Nullable Output<String> stackName;

    /**
     * @return The stack name. Set when the webhook is scoped to a specific stack.
     * 
     */
    public Optional<Output<String>> stackName() {
        return Optional.ofNullable(this.stackName);
    }

    private Webhook_esc_environmentsArgs() {}

    private Webhook_esc_environmentsArgs(Webhook_esc_environmentsArgs $) {
        this.active = $.active;
        this.displayName = $.displayName;
        this.envName = $.envName;
        this.filters = $.filters;
        this.format = $.format;
        this.groups = $.groups;
        this.name = $.name;
        this.organizationName = $.organizationName;
        this.payloadUrl = $.payloadUrl;
        this.projectName = $.projectName;
        this.secret = $.secret;
        this.stackName = $.stackName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(Webhook_esc_environmentsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Webhook_esc_environmentsArgs $;

        public Builder() {
            $ = new Webhook_esc_environmentsArgs();
        }

        public Builder(Webhook_esc_environmentsArgs defaults) {
            $ = new Webhook_esc_environmentsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param active Whether the webhook is active and will receive deliveries.
         * 
         * @return builder
         * 
         */
        public Builder active(Output<Boolean> active) {
            $.active = active;
            return this;
        }

        /**
         * @param active Whether the webhook is active and will receive deliveries.
         * 
         * @return builder
         * 
         */
        public Builder active(Boolean active) {
            return active(Output.of(active));
        }

        /**
         * @param displayName The human-readable display name shown in the UI.
         * 
         * @return builder
         * 
         */
        public Builder displayName(Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        /**
         * @param displayName The human-readable display name shown in the UI.
         * 
         * @return builder
         * 
         */
        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        /**
         * @param envName The environment name. Set when the webhook is scoped to a specific environment.
         * 
         * @return builder
         * 
         */
        public Builder envName(Output<String> envName) {
            $.envName = envName;
            return this;
        }

        /**
         * @param envName The environment name. Set when the webhook is scoped to a specific environment.
         * 
         * @return builder
         * 
         */
        public Builder envName(String envName) {
            return envName(Output.of(envName));
        }

        /**
         * @param filters Specific event types this webhook subscribes to. If empty, all events are delivered.
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable Output<List<String>> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters Specific event types this webhook subscribes to. If empty, all events are delivered.
         * 
         * @return builder
         * 
         */
        public Builder filters(List<String> filters) {
            return filters(Output.of(filters));
        }

        /**
         * @param filters Specific event types this webhook subscribes to. If empty, all events are delivered.
         * 
         * @return builder
         * 
         */
        public Builder filters(String... filters) {
            return filters(List.of(filters));
        }

        /**
         * @param format The format of the webhook payload (e.g., &#39;raw&#39;, &#39;slack&#39;, &#39;ms_teams&#39;).
         * 
         * @return builder
         * 
         */
        public Builder format(@Nullable Output<String> format) {
            $.format = format;
            return this;
        }

        /**
         * @param format The format of the webhook payload (e.g., &#39;raw&#39;, &#39;slack&#39;, &#39;ms_teams&#39;).
         * 
         * @return builder
         * 
         */
        public Builder format(String format) {
            return format(Output.of(format));
        }

        /**
         * @param groups Event groups this webhook subscribes to (e.g., &#39;stacks&#39;, &#39;deployments&#39;).
         * 
         * @return builder
         * 
         */
        public Builder groups(@Nullable Output<List<String>> groups) {
            $.groups = groups;
            return this;
        }

        /**
         * @param groups Event groups this webhook subscribes to (e.g., &#39;stacks&#39;, &#39;deployments&#39;).
         * 
         * @return builder
         * 
         */
        public Builder groups(List<String> groups) {
            return groups(Output.of(groups));
        }

        /**
         * @param groups Event groups this webhook subscribes to (e.g., &#39;stacks&#39;, &#39;deployments&#39;).
         * 
         * @return builder
         * 
         */
        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }

        /**
         * @param name The unique identifier name for the webhook within its scope.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The unique identifier name for the webhook within its scope.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param organizationName The organization that owns this webhook.
         * 
         * @return builder
         * 
         */
        public Builder organizationName(Output<String> organizationName) {
            $.organizationName = organizationName;
            return this;
        }

        /**
         * @param organizationName The organization that owns this webhook.
         * 
         * @return builder
         * 
         */
        public Builder organizationName(String organizationName) {
            return organizationName(Output.of(organizationName));
        }

        /**
         * @param payloadUrl The URL to which webhook payloads are delivered.
         * 
         * @return builder
         * 
         */
        public Builder payloadUrl(Output<String> payloadUrl) {
            $.payloadUrl = payloadUrl;
            return this;
        }

        /**
         * @param payloadUrl The URL to which webhook payloads are delivered.
         * 
         * @return builder
         * 
         */
        public Builder payloadUrl(String payloadUrl) {
            return payloadUrl(Output.of(payloadUrl));
        }

        /**
         * @param projectName The project name. Set when the webhook is scoped to a specific stack.
         * 
         * @return builder
         * 
         */
        public Builder projectName(Output<String> projectName) {
            $.projectName = projectName;
            return this;
        }

        /**
         * @param projectName The project name. Set when the webhook is scoped to a specific stack.
         * 
         * @return builder
         * 
         */
        public Builder projectName(String projectName) {
            return projectName(Output.of(projectName));
        }

        /**
         * @param secret Secret will be omitted when returned from the service.
         * 
         * @return builder
         * 
         */
        public Builder secret(@Nullable Output<String> secret) {
            $.secret = secret;
            return this;
        }

        /**
         * @param secret Secret will be omitted when returned from the service.
         * 
         * @return builder
         * 
         */
        public Builder secret(String secret) {
            return secret(Output.of(secret));
        }

        /**
         * @param stackName The stack name. Set when the webhook is scoped to a specific stack.
         * 
         * @return builder
         * 
         */
        public Builder stackName(@Nullable Output<String> stackName) {
            $.stackName = stackName;
            return this;
        }

        /**
         * @param stackName The stack name. Set when the webhook is scoped to a specific stack.
         * 
         * @return builder
         * 
         */
        public Builder stackName(String stackName) {
            return stackName(Output.of(stackName));
        }

        public Webhook_esc_environmentsArgs build() {
            if ($.active == null) {
                throw new MissingRequiredPropertyException("Webhook_esc_environmentsArgs", "active");
            }
            if ($.displayName == null) {
                throw new MissingRequiredPropertyException("Webhook_esc_environmentsArgs", "displayName");
            }
            if ($.envName == null) {
                throw new MissingRequiredPropertyException("Webhook_esc_environmentsArgs", "envName");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("Webhook_esc_environmentsArgs", "name");
            }
            if ($.organizationName == null) {
                throw new MissingRequiredPropertyException("Webhook_esc_environmentsArgs", "organizationName");
            }
            if ($.payloadUrl == null) {
                throw new MissingRequiredPropertyException("Webhook_esc_environmentsArgs", "payloadUrl");
            }
            if ($.projectName == null) {
                throw new MissingRequiredPropertyException("Webhook_esc_environmentsArgs", "projectName");
            }
            return $;
        }
    }

}
