package pulumiapi

// Constants extracted to satisfy the goconst linter for repeated string
// literals that occur only in test files.
const (
	tokenNotFoundError    = "token not found"
	tokenIDKey            = "token_id"
	secretKey             = "secret"
	userTokPath           = "/api/user/tokens"
	unauthorizedError     = "unauthorized"
	otherValue            = "other"
	notFoundError         = "not found"
	projectKey            = "project"
	awsProvider           = "aws"
	testEnvName           = "test-env"
	regionsKey            = "regions"
	internalServerError   = "internal server error"
	environmentKey        = "environment"
	testTimestamp         = "2025-01-01T00:00:00Z"
	teamKey               = "team"
	validTag              = "valid-tag"
	valueKey              = "value"
	memberUserPath        = "/api/orgs/an-organization/members/a-user"
	membersPath           = "/api/orgs/an-organization/members"
	bobUser               = "bob"
	orgTokPath            = "/api/orgs/anOrg/tokens"
	policyGroupsPath      = "/api/orgs/test-org/policygroups"
	policyPackVersion     = "1.0.0"
	policyPackVersionPath = "/api/orgs/anOrg/policypacks/alpha/versions/1.0.0"
	readOnlyRoleName      = "read-only"
	readOnlyDescription   = "read only access"
	globalScope           = "global"
	stackKey              = "stack"
	organizationKey       = "organization"
	aliceUser             = "alice"
	teamPath              = "/api/orgs/an-organization/teams/a-team"
	defaultValue          = "Default"
	teamRolesPath         = "/api/orgs/an-organization/teams/a-team/roles"
	hooksPath             = "/api/orgs/an-organization/hooks"
	webhookPath           = "/api/orgs/an-organization/hooks/a-webhook"
	usWest2Region         = "us-west-2"
	alphaPolicyPack       = "alpha"
)
