// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.Api
{
    /// <summary>
    /// Manages a single membership edge through UpdatePolicyGroup (addStack / removeStack).
    /// </summary>
    [PulumiServiceResourceType("pulumiservice:api:PolicyGroupStackAttachment")]
    public partial class PolicyGroupStackAttachment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The organization name
        /// </summary>
        [Output("orgName")]
        public Output<string> OrgName { get; private set; } = null!;

        /// <summary>
        /// The policy group name
        /// </summary>
        [Output("policyGroup")]
        public Output<string> PolicyGroup { get; private set; } = null!;

        /// <summary>
        /// The routing project
        /// </summary>
        [Output("routingProject")]
        public Output<string> RoutingProject { get; private set; } = null!;


        /// <summary>
        /// Create a PolicyGroupStackAttachment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PolicyGroupStackAttachment(string name, PolicyGroupStackAttachmentArgs args, CustomResourceOptions? options = null)
            : base("pulumiservice:api:PolicyGroupStackAttachment", name, args ?? new PolicyGroupStackAttachmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PolicyGroupStackAttachment(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pulumiservice:api:PolicyGroupStackAttachment", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PolicyGroupStackAttachment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PolicyGroupStackAttachment Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PolicyGroupStackAttachment(name, id, options);
        }
    }

    public sealed class PolicyGroupStackAttachmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The organization name
        /// </summary>
        [Input("orgName", required: true)]
        public Input<string> OrgName { get; set; } = null!;

        /// <summary>
        /// The policy group name
        /// </summary>
        [Input("policyGroup", required: true)]
        public Input<string> PolicyGroup { get; set; } = null!;

        /// <summary>
        /// The routing project
        /// </summary>
        [Input("routingProject", required: true)]
        public Input<string> RoutingProject { get; set; } = null!;

        public PolicyGroupStackAttachmentArgs()
        {
        }
        public static new PolicyGroupStackAttachmentArgs Empty => new PolicyGroupStackAttachmentArgs();
    }
}
