[project]
  name = "pulumi_pulumiservice"
  description = "A native Pulumi package for creating and managing Pulumi Cloud constructs"
  dependencies = ["parver>=0.2.1", "pulumi>=3.0.0,<4.0.0", "semver>=2.8.1", "typing-extensions>=4.11; python_version < \"3.11\""]
  keywords = ["pulumi", "kind/native", "category/infrastructure"]
  readme = "README.md"
  requires-python = ">=3.8"
  version = "0.29.4+dev"
  [project.license]
    text = "Apache-2.0"
  [project.urls]
    Homepage = "https://pulumi.com"
    Repository = "https://github.com/pulumi/pulumi-pulumiservice"

[build-system]
  requires = ["setuptools>=61.0"]
  build-backend = "setuptools.build_meta"

[tool]
  [tool.setuptools]
    [tool.setuptools.package-data]
      pulumi_pulumiservice = ["py.typed", "pulumi-plugin.json"]
