// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumiservice

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a deployment on a stack. This is an async operation and will return immediately after the deployment is created, not waiting for the deployment to complete.
func CreateDeployment(ctx *pulumi.Context, args *CreateDeploymentArgs, opts ...pulumi.InvokeOption) (*CreateDeploymentResult, error) {
	var rv CreateDeploymentResult
	err := ctx.Invoke("pulumiservice:index:CreateDeployment", args.Defaults(), &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type CreateDeploymentArgs struct {
	InheritSettings *bool   `pulumi:"inheritSettings"`
	Operation       *string `pulumi:"operation"`
	Organization    string  `pulumi:"organization"`
	Project         string  `pulumi:"project"`
	Stack           string  `pulumi:"stack"`
}

// Defaults sets the appropriate defaults for CreateDeploymentArgs
func (val *CreateDeploymentArgs) Defaults() *CreateDeploymentArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.InheritSettings == nil {
		inheritSettings_ := true
		tmp.InheritSettings = &inheritSettings_
	}
	if tmp.Operation == nil {
		operation_ := "update"
		tmp.Operation = &operation_
	}
	return &tmp
}

type CreateDeploymentResult struct {
	ConsoleUrl string  `pulumi:"consoleUrl"`
	Id         string  `pulumi:"id"`
	Version    float64 `pulumi:"version"`
}

func CreateDeploymentOutput(ctx *pulumi.Context, args CreateDeploymentOutputArgs, opts ...pulumi.InvokeOption) CreateDeploymentResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (CreateDeploymentResult, error) {
			args := v.(CreateDeploymentArgs)
			r, err := CreateDeployment(ctx, &args, opts...)
			var s CreateDeploymentResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(CreateDeploymentResultOutput)
}

type CreateDeploymentOutputArgs struct {
	InheritSettings pulumi.BoolPtrInput   `pulumi:"inheritSettings"`
	Operation       pulumi.StringPtrInput `pulumi:"operation"`
	Organization    pulumi.StringInput    `pulumi:"organization"`
	Project         pulumi.StringInput    `pulumi:"project"`
	Stack           pulumi.StringInput    `pulumi:"stack"`
}

func (CreateDeploymentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateDeploymentArgs)(nil)).Elem()
}

type CreateDeploymentResultOutput struct{ *pulumi.OutputState }

func (CreateDeploymentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CreateDeploymentResult)(nil)).Elem()
}

func (o CreateDeploymentResultOutput) ToCreateDeploymentResultOutput() CreateDeploymentResultOutput {
	return o
}

func (o CreateDeploymentResultOutput) ToCreateDeploymentResultOutputWithContext(ctx context.Context) CreateDeploymentResultOutput {
	return o
}

func (o CreateDeploymentResultOutput) ConsoleUrl() pulumi.StringOutput {
	return o.ApplyT(func(v CreateDeploymentResult) string { return v.ConsoleUrl }).(pulumi.StringOutput)
}

func (o CreateDeploymentResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v CreateDeploymentResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o CreateDeploymentResultOutput) Version() pulumi.Float64Output {
	return o.ApplyT(func(v CreateDeploymentResult) float64 { return v.Version }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterOutputType(CreateDeploymentResultOutput{})
}
