# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities

__all__ = ['TeamArgs', 'Team']

@pulumi.input_type
class TeamArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[_builtins.str],
                 display_name: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 org_name: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a Team resource.

        :param pulumi.Input[_builtins.str] description: The description
        :param pulumi.Input[_builtins.str] display_name: The display name
        :param pulumi.Input[_builtins.str] name: The name
        :param pulumi.Input[_builtins.str] org_name: The organization name
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "org_name", org_name)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str]:
        """
        The description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str]:
        """
        The display name
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="orgName")
    def org_name(self) -> pulumi.Input[_builtins.str]:
        """
        The organization name
        """
        return pulumi.get(self, "org_name")

    @org_name.setter
    def org_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "org_name", value)


@pulumi.type_token("pulumiservice:v2/teams:Team")
class Team(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 org_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        CreatePulumiTeam creates a "Pulumi" team, i.e. one whose membership is managed by Pulumi.
        (As opposed to a GitHub or GitLab-based team.)


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: The description
        :param pulumi.Input[_builtins.str] display_name: The display name
        :param pulumi.Input[_builtins.str] name: The name
        :param pulumi.Input[_builtins.str] org_name: The organization name
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TeamArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        CreatePulumiTeam creates a "Pulumi" team, i.e. one whose membership is managed by Pulumi.
        (As opposed to a GitHub or GitLab-based team.)


        :param str resource_name: The name of the resource.
        :param TeamArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TeamArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 org_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TeamArgs.__new__(TeamArgs)

            if description is None and not opts.urn:
                raise TypeError("Missing required property 'description'")
            __props__.__dict__["description"] = description
            if display_name is None and not opts.urn:
                raise TypeError("Missing required property 'display_name'")
            __props__.__dict__["display_name"] = display_name
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if org_name is None and not opts.urn:
                raise TypeError("Missing required property 'org_name'")
            __props__.__dict__["org_name"] = org_name
            __props__.__dict__["accounts"] = None
            __props__.__dict__["environments"] = None
            __props__.__dict__["kind"] = None
            __props__.__dict__["list_members_error"] = None
            __props__.__dict__["members"] = None
            __props__.__dict__["role_ids"] = None
            __props__.__dict__["stacks"] = None
            __props__.__dict__["user_role"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["name", "orgName"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Team, __self__).__init__(
            'pulumiservice:v2/teams:Team',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Team':
        """
        Get an existing Team resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = TeamArgs.__new__(TeamArgs)

        __props__.__dict__["accounts"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["display_name"] = None
        __props__.__dict__["environments"] = None
        __props__.__dict__["kind"] = None
        __props__.__dict__["list_members_error"] = None
        __props__.__dict__["members"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["org_name"] = None
        __props__.__dict__["role_ids"] = None
        __props__.__dict__["stacks"] = None
        __props__.__dict__["user_role"] = None
        return Team(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def accounts(self) -> pulumi.Output[Optional[Sequence[Any]]]:
        """
        The list of account permissions granted to the team.
        """
        return pulumi.get(self, "accounts")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        A free-form text description of the team's purpose.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[_builtins.str]:
        """
        The human-readable display name shown in the UI.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def environments(self) -> pulumi.Output[Optional[Sequence[Any]]]:
        """
        The list of environment settings for the team.
        """
        return pulumi.get(self, "environments")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Output[_builtins.str]:
        """
        The kind of team (e.g., pulumi or GitHub-backed).
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter(name="listMembersError")
    def list_members_error(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        ListMembersError is the error message if an error was encountered whilst trying to
        contact the team's backend (eg. GitHub). The UI will only show this error if it is non-nil
        and if Members itself is an empty slice.
        """
        return pulumi.get(self, "list_members_error")

    @_builtins.property
    @pulumi.getter
    def members(self) -> pulumi.Output[Optional[Sequence[Any]]]:
        """
        The list of team members.
        """
        return pulumi.get(self, "members")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The unique identifier name of the team within the organization.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="orgName")
    def org_name(self) -> pulumi.Output[_builtins.str]:
        """
        The organization name
        """
        return pulumi.get(self, "org_name")

    @_builtins.property
    @pulumi.getter(name="roleIds")
    def role_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        RoleIDs are the IDs of the FGA roles assigned to the team, if any.
        Currently only one role per team is supported.
        """
        return pulumi.get(self, "role_ids")

    @_builtins.property
    @pulumi.getter
    def stacks(self) -> pulumi.Output[Optional[Sequence[Any]]]:
        """
        The list of stack permissions granted to the team.
        """
        return pulumi.get(self, "stacks")

    @_builtins.property
    @pulumi.getter(name="userRole")
    def user_role(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        UserRole is the calling user's role on the given team.
        """
        return pulumi.get(self, "user_role")

