// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.api.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.pulumiservice.api.inputs.DockerImageCredentialsRequestArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * DockerImageRequest is the request body for specifying a Docker image and its credentials.
 * 
 */
public final class DockerImageRequestArgs extends com.pulumi.resources.ResourceArgs {

    public static final DockerImageRequestArgs Empty = new DockerImageRequestArgs();

    /**
     * The credentials needed to pull the Docker image.
     * 
     */
    @Import(name="credentials")
    private @Nullable Output<DockerImageCredentialsRequestArgs> credentials;

    /**
     * @return The credentials needed to pull the Docker image.
     * 
     */
    public Optional<Output<DockerImageCredentialsRequestArgs>> credentials() {
        return Optional.ofNullable(this.credentials);
    }

    /**
     * The Docker image reference (e.g. registry/image:tag).
     * 
     */
    @Import(name="reference")
    private @Nullable Output<String> reference;

    /**
     * @return The Docker image reference (e.g. registry/image:tag).
     * 
     */
    public Optional<Output<String>> reference() {
        return Optional.ofNullable(this.reference);
    }

    private DockerImageRequestArgs() {}

    private DockerImageRequestArgs(DockerImageRequestArgs $) {
        this.credentials = $.credentials;
        this.reference = $.reference;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DockerImageRequestArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DockerImageRequestArgs $;

        public Builder() {
            $ = new DockerImageRequestArgs();
        }

        public Builder(DockerImageRequestArgs defaults) {
            $ = new DockerImageRequestArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param credentials The credentials needed to pull the Docker image.
         * 
         * @return builder
         * 
         */
        public Builder credentials(@Nullable Output<DockerImageCredentialsRequestArgs> credentials) {
            $.credentials = credentials;
            return this;
        }

        /**
         * @param credentials The credentials needed to pull the Docker image.
         * 
         * @return builder
         * 
         */
        public Builder credentials(DockerImageCredentialsRequestArgs credentials) {
            return credentials(Output.of(credentials));
        }

        /**
         * @param reference The Docker image reference (e.g. registry/image:tag).
         * 
         * @return builder
         * 
         */
        public Builder reference(@Nullable Output<String> reference) {
            $.reference = reference;
            return this;
        }

        /**
         * @param reference The Docker image reference (e.g. registry/image:tag).
         * 
         * @return builder
         * 
         */
        public Builder reference(String reference) {
            return reference(Output.of(reference));
        }

        public DockerImageRequestArgs build() {
            return $;
        }
    }

}
