// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.api.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PermissionLiteralExpressionBoolArgs extends com.pulumi.resources.ResourceArgs {

    public static final PermissionLiteralExpressionBoolArgs Empty = new PermissionLiteralExpressionBoolArgs();

    /**
     * Expected value is &#39;PermissionLiteralExpressionBool&#39;.
     * 
     */
    @Import(name="type__", required=true)
    private Output<String> type__;

    /**
     * @return Expected value is &#39;PermissionLiteralExpressionBool&#39;.
     * 
     */
    public Output<String> type__() {
        return this.type__;
    }

    /**
     * The boolean literal value.
     * 
     */
    @Import(name="value")
    private @Nullable Output<Boolean> value;

    /**
     * @return The boolean literal value.
     * 
     */
    public Optional<Output<Boolean>> value() {
        return Optional.ofNullable(this.value);
    }

    private PermissionLiteralExpressionBoolArgs() {}

    private PermissionLiteralExpressionBoolArgs(PermissionLiteralExpressionBoolArgs $) {
        this.type__ = $.type__;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PermissionLiteralExpressionBoolArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PermissionLiteralExpressionBoolArgs $;

        public Builder() {
            $ = new PermissionLiteralExpressionBoolArgs();
        }

        public Builder(PermissionLiteralExpressionBoolArgs defaults) {
            $ = new PermissionLiteralExpressionBoolArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param type__ Expected value is &#39;PermissionLiteralExpressionBool&#39;.
         * 
         * @return builder
         * 
         */
        public Builder type__(Output<String> type__) {
            $.type__ = type__;
            return this;
        }

        /**
         * @param type__ Expected value is &#39;PermissionLiteralExpressionBool&#39;.
         * 
         * @return builder
         * 
         */
        public Builder type__(String type__) {
            return type__(Output.of(type__));
        }

        /**
         * @param value The boolean literal value.
         * 
         * @return builder
         * 
         */
        public Builder value(@Nullable Output<Boolean> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value The boolean literal value.
         * 
         * @return builder
         * 
         */
        public Builder value(Boolean value) {
            return value(Output.of(value));
        }

        public PermissionLiteralExpressionBoolArgs build() {
            $.type__ = Codegen.stringProp("type__").output().arg($.type__).require();
            return $;
        }
    }

}
