// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.pulumiservice.OrganizationRoleArgs;
import com.pulumi.pulumiservice.Utilities;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A custom (fine-grained) role defined on a Pulumi Cloud organization. Custom roles allow precise permission control beyond the built-in `admin` / `member` / `billing-manager` roles. Assign them to members via the `OrganizationMember.roleId` field or to teams via `TeamRoleAssignment`.
 * 
 * Requires the Custom Roles feature to be enabled on the organization. See the [Pulumi Cloud RBAC docs](https://www.pulumi.com/docs/pulumi-cloud/access-management/rbac/) for the shape of the `permissions` descriptor.
 * 
 * This resource manages only permission descriptors with `uxPurpose=&#34;role&#34;`. Pulumi Cloud uses `uxPurpose` to split the permission-descriptor table into roles and other kinds (for example `policy`). Use `pulumiservice:api:Role`, which exposes `uxPurpose` directly, to manage the other kinds.
 * 
 * Build the role&#39;s `permissions` with the `buildRolePermissions` helper function, as in the example below.
 * 
 * ## Example Usage
 * ### A role with organization-level access and entity rules
 * 
 * The program looks up an existing stack, environment, and Insights account, then defines two roles: one granting scopes directly, and one granting permission sets through a policy.
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.pulumiservice.enums.RbacEnvironmentScope;
 * import com.pulumi.pulumiservice.enums.RbacInsightsAccountScope;
 * import com.pulumi.pulumiservice.enums.RbacOrganizationScope;
 * import com.pulumi.pulumiservice.enums.RbacStackScope;
 * import com.pulumi.pulumiservice.enums.RoleTagOperator;
 * import com.pulumi.pulumiservice.PulumiserviceFunctions;
 * import com.pulumi.pulumiservice.inputs.GetStackArgs;
 * import com.pulumi.pulumiservice.inputs.GetEnvironmentArgs;
 * import com.pulumi.pulumiservice.inputs.GetInsightsAccountArgs;
 * import com.pulumi.pulumiservice.inputs.BuildEnvironmentScopedPermissionsArgs;
 * import com.pulumi.pulumiservice.inputs.BuildRolePermissionsArgs;
 * import com.pulumi.pulumiservice.inputs.RoleStackRuleArgs;
 * import com.pulumi.pulumiservice.inputs.RoleTagConditionArgs;
 * import com.pulumi.pulumiservice.inputs.RoleEnvironmentRuleArgs;
 * import com.pulumi.pulumiservice.inputs.RoleInsightsAccountRuleArgs;
 * import com.pulumi.pulumiservice.inputs.GetOrganizationPermissionSetArgs;
 * import com.pulumi.pulumiservice.inputs.RolePermissionSetRefArgs;
 * import com.pulumi.pulumiservice.api.Role;
 * import com.pulumi.pulumiservice.api.RoleArgs;
 * import com.pulumi.pulumiservice.inputs.BuildComposePermissionsArgs;
 * import com.pulumi.pulumiservice.OrganizationRole;
 * import com.pulumi.pulumiservice.OrganizationRoleArgs;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         final var config = ctx.config();
 *         final var organizationName = config.get("organizationName").orElse("my-org");
 *         final var prodStack = PulumiserviceFunctions.getStack(GetStackArgs.builder()
 *             .organizationName(organizationName)
 *             .projectName("networking")
 *             .stackName("prod")
 *             .build());
 * 
 *         final var sharedEnvironment = PulumiserviceFunctions.getEnvironment(GetEnvironmentArgs.builder()
 *             .organizationName(organizationName)
 *             .projectName("platform")
 *             .name("shared")
 *             .build());
 * 
 *         final var awsAccount = PulumiserviceFunctions.getInsightsAccount(GetInsightsAccountArgs.builder()
 *             .organizationName(organizationName)
 *             .accountName("aws-production")
 *             .build());
 * 
 *         final var sharedEnvironmentRotate = PulumiserviceFunctions.buildEnvironmentScopedPermissions(BuildEnvironmentScopedPermissionsArgs.builder()
 *             .environmentId(sharedEnvironment.applyValue(_sharedEnvironment -> _sharedEnvironment.environmentId()))
 *             .permissions("environment:rotate")
 *             .build());
 * 
 *         final var platformPermissions = PulumiserviceFunctions.buildRolePermissions(BuildRolePermissionsArgs.builder()
 *             .organizationScopes(            
 *                 RbacOrganizationScope.TeamRead,
 *                 RbacOrganizationScope.StackCreate)
 *             .stackRules(            
 *                 // Read every stack in the organization
 *                 RoleStackRuleArgs.builder()
 *                     .all(true)
 *                     .scopes(RbacStackScope.StackRead)
 *                     .build(),
 *                 // Deploy one specific stack
 *                 RoleStackRuleArgs.builder()
 *                     .id(prodStack.applyValue(_prodStack -> _prodStack.stackId()))
 *                     .scopes(                    
 *                         RbacStackScope.StackWrite,
 *                         RbacStackScope.StackDeploymentCreate)
 *                     .build(),
 *                 // Deploy stacks tagged team=platform (the operator defaults to equals)
 *                 RoleStackRuleArgs.builder()
 *                     .tags(RoleTagConditionArgs.builder()
 *                         .key("team")
 *                         .value("platform")
 *                         .build())
 *                     .scopes(                    
 *                         RbacStackScope.StackWrite,
 *                         RbacStackScope.StackDeploymentCreate)
 *                     .build(),
 *                 // Deploy stacks whose env tag is anything but "prod"
 *                 RoleStackRuleArgs.builder()
 *                     .tags(RoleTagConditionArgs.builder()
 *                         .key("env")
 *                         .value("prod")
 *                         .operator(RoleTagOperator.NotEquals)
 *                         .build())
 *                     .scopes(                    
 *                         RbacStackScope.StackWrite,
 *                         RbacStackScope.StackDeploymentCreate)
 *                     .build(),
 *                 // Read deployment settings on stacks that have a cost-center tag, whatever its value
 *                 RoleStackRuleArgs.builder()
 *                     .tags(RoleTagConditionArgs.builder()
 *                         .key("cost-center")
 *                         .build())
 *                     .scopes(RbacStackScope.StackDeploymentSettingsRead)
 *                     .build(),
 *                 // Delete stacks that match every tag condition
 *                 RoleStackRuleArgs.builder()
 *                     .tags(                    
 *                         RoleTagConditionArgs.builder()
 *                             .key("team")
 *                             .value("platform")
 *                             .build(),
 *                         RoleTagConditionArgs.builder()
 *                             .key("lifecycle")
 *                             .value("ephemeral")
 *                             .build())
 *                     .scopes(RbacStackScope.StackDelete)
 *                     .build())
 *             .environmentRules(            
 *                 // Read every environment
 *                 RoleEnvironmentRuleArgs.builder()
 *                     .all(true)
 *                     .scopes(RbacEnvironmentScope.EnvironmentRead)
 *                     .build(),
 *                 // Open and update one specific environment
 *                 RoleEnvironmentRuleArgs.builder()
 *                     .id(sharedEnvironment.applyValue(_sharedEnvironment -> _sharedEnvironment.environmentId()))
 *                     .scopes(                    
 *                         RbacEnvironmentScope.EnvironmentOpen,
 *                         RbacEnvironmentScope.EnvironmentWrite)
 *                     .build(),
 *                 // Open environments tagged team=platform
 *                 RoleEnvironmentRuleArgs.builder()
 *                     .tags(RoleTagConditionArgs.builder()
 *                         .key("team")
 *                         .value("platform")
 *                         .build())
 *                     .scopes(RbacEnvironmentScope.EnvironmentOpen)
 *                     .build())
 *             .insightsAccountRules(            
 *                 // Read every Insights account
 *                 RoleInsightsAccountRuleArgs.builder()
 *                     .all(true)
 *                     .scopes(RbacInsightsAccountScope.InsightsAccountRead)
 *                     .build(),
 *                 // Scan one specific account
 *                 RoleInsightsAccountRuleArgs.builder()
 *                     .id(awsAccount.applyValue(_awsAccount -> _awsAccount.insightsAccountId()))
 *                     .scopes(RbacInsightsAccountScope.InsightsAccountScan)
 *                     .build(),
 *                 // Update accounts tagged team=platform
 *                 RoleInsightsAccountRuleArgs.builder()
 *                     .tags(RoleTagConditionArgs.builder()
 *                         .key("team")
 *                         .value("platform")
 *                         .build())
 *                     .scopes(RbacInsightsAccountScope.InsightsAccountUpdate)
 *                     .build())
 *             .additionalEntries(sharedEnvironmentRotate.applyValue(_sharedEnvironmentRotate -> _sharedEnvironmentRotate.permissions()))
 *             .build());
 * 
 *         final var orgReadOnly = PulumiserviceFunctions.getOrganizationPermissionSet(GetOrganizationPermissionSetArgs.builder()
 *             .organizationName(organizationName)
 *             .defaultIdentifier("org-settings-read-only")
 *             .build());
 * 
 *         final var stackWrite = PulumiserviceFunctions.getOrganizationPermissionSet(GetOrganizationPermissionSetArgs.builder()
 *             .organizationName(organizationName)
 *             .defaultIdentifier("stack-write")
 *             .build());
 * 
 *         final var environmentRead = PulumiserviceFunctions.getOrganizationPermissionSet(GetOrganizationPermissionSetArgs.builder()
 *             .organizationName(organizationName)
 *             .defaultIdentifier("environment-read")
 *             .build());
 * 
 *         final var insightsAccountRead = PulumiserviceFunctions.getOrganizationPermissionSet(GetOrganizationPermissionSetArgs.builder()
 *             .organizationName(organizationName)
 *             .defaultIdentifier("insights-account-read")
 *             .build());
 * 
 *         final var operatorPolicyPermissions = PulumiserviceFunctions.buildRolePermissions(BuildRolePermissionsArgs.builder()
 *             .organizationPermissionSets(RolePermissionSetRefArgs.builder()
 *                 .permissionSetId(orgReadOnly.applyValue(_orgReadOnly -> _orgReadOnly.permissionSetId()))
 *                 .resourceType(orgReadOnly.applyValue(_orgReadOnly -> _orgReadOnly.resourceType()))
 *                 .build())
 *             // The Stack Write set on stacks tagged team=platform
 *             .stackRules(RoleStackRuleArgs.builder()
 *                 .tags(RoleTagConditionArgs.builder()
 *                     .key("team")
 *                     .value("platform")
 *                     .build())
 *                 .permissionSets(RolePermissionSetRefArgs.builder()
 *                     .permissionSetId(stackWrite.applyValue(_stackWrite -> _stackWrite.permissionSetId()))
 *                     .resourceType(stackWrite.applyValue(_stackWrite -> _stackWrite.resourceType()))
 *                     .build())
 *                 .build())
 *             // The Environment Read set on every environment
 *             .environmentRules(RoleEnvironmentRuleArgs.builder()
 *                 .all(true)
 *                 .permissionSets(RolePermissionSetRefArgs.builder()
 *                     .permissionSetId(environmentRead.applyValue(_environmentRead -> _environmentRead.permissionSetId()))
 *                     .resourceType(environmentRead.applyValue(_environmentRead -> _environmentRead.resourceType()))
 *                     .build())
 *                 .build())
 *             // The Insights Account Read set, plus one extra scope, on one account
 *             .insightsAccountRules(RoleInsightsAccountRuleArgs.builder()
 *                 .id(awsAccount.applyValue(_awsAccount -> _awsAccount.insightsAccountId()))
 *                 .permissionSets(RolePermissionSetRefArgs.builder()
 *                     .permissionSetId(insightsAccountRead.applyValue(_insightsAccountRead -> _insightsAccountRead.permissionSetId()))
 *                     .resourceType(insightsAccountRead.applyValue(_insightsAccountRead -> _insightsAccountRead.resourceType()))
 *                     .build())
 *                 .scopes(RbacInsightsAccountScope.InsightsAccountScan)
 *                 .build())
 *             .build());
 * 
 *         var operatorPolicy = new Role("operatorPolicy", RoleArgs.builder()
 *             .orgName(organizationName)
 *             .name("Platform Operators policy")
 *             .uxPurpose("policy")
 *             .details(operatorPolicyPermissions.applyValue(_operatorPolicyPermissions -> _operatorPolicyPermissions.permissions()))
 *             .build());
 * 
 *         final var operatorPermissions = PulumiserviceFunctions.buildComposePermissions(BuildComposePermissionsArgs.builder()
 *             .ids(operatorPolicy.roleID())
 *             .build());
 * 
 *         var platformRole = new OrganizationRole("platformRole", OrganizationRoleArgs.builder()
 *             .organizationName(organizationName)
 *             .name("Platform Engineers")
 *             .description("Read access across the organization, plus deploy access to platform stacks.")
 *             .permissions(platformPermissions.applyValue(_platformPermissions -> _platformPermissions.permissions()))
 *             .build());
 * 
 *         var operatorRole = new OrganizationRole("operatorRole", OrganizationRoleArgs.builder()
 *             .organizationName(organizationName)
 *             .name("Platform Operators")
 *             .description("Built-in permission sets on platform entities.")
 *             .permissions(operatorPermissions.applyValue(_operatorPermissions -> _operatorPermissions.permissions()))
 *             .build());
 * 
 *     }
 * }
 * 
 * }
 * </pre>
 * 
 */
@ResourceType(type="pulumiservice:index:OrganizationRole")
public class OrganizationRole extends com.pulumi.resources.CustomResource {
    /**
     * Human-readable description of what the role grants.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Human-readable description of what the role grants.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * The role&#39;s display name. Must be unique within the organization.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The role&#39;s display name. Must be unique within the organization.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The Pulumi Cloud organization name.
     * 
     */
    @Export(name="organizationName", refs={String.class}, tree="[0]")
    private Output<String> organizationName;

    /**
     * @return The Pulumi Cloud organization name.
     * 
     */
    public Output<String> organizationName() {
        return this.organizationName;
    }
    /**
     * The role&#39;s permission descriptor tree.
     * 
     * **Build this with the helper functions.** They construct the tree for you and validate it before anything reaches Pulumi Cloud:
     * - `buildRolePermissions`: start here. It builds a complete role from organization-level access and rules for stacks, environments, and Insights accounts. Each rule grants scopes and/or permission sets on every entity of its type, on one specific entity, or on entities matching tags. Each rule list accepts only scopes and permission sets for its own entity type, so a stack scope can&#39;t end up on an environment rule.
     * - `buildAllowPermissions`: grants scopes with no conditions.
     * - `buildStackScopedPermissions`, `buildEnvironmentScopedPermissions`, and `buildInsightsAccountScopedPermissions`: grant scopes on one specific entity.
     * - `buildComposePermissions`: grants a policy by ID (see below).
     * 
     * Combine helpers by passing their `permissions` outputs to `buildRolePermissions.additionalEntries`. Look up stack IDs with `getStack`, environment IDs with `getEnvironment`, and Insights account IDs with `getInsightsAccount`. To assign the role, use `TeamRoleAssignment` or `OrganizationMember.roleId`.
     * 
     * **Permission sets** (bundles of scopes such as the built-in Stack Write, looked up with `getOrganizationPermissionSet`) can&#39;t be referenced from a role directly: Pulumi Cloud accepts them only in a policy. Build the policy&#39;s permissions with `buildRolePermissions` (`permissionSets`, `organizationPermissionSets`), store them with `pulumiservice:api:Role` (`uxPurpose: policy`), and set this property to `buildComposePermissions` with the policy&#39;s `roleID`. The example below shows both approaches.
     * 
     * **When the helpers can&#39;t express what you need**, write that part as a raw descriptor in the Pulumi Cloud wire format, using the `__type` field to name each node. For example:
     * 
     * Pass it to `buildRolePermissions.additionalEntries`, which keeps the rest of the role on helpers, or assign it to this property directly. The node types are:
     * - `PermissionDescriptorAllow`: `{permissions: [&lt;scope&gt;, ...]}` grants the listed scopes.
     * - `PermissionDescriptorGroup`: `{entries: [&lt;descriptor&gt;, ...]}` grants the union of its entries.
     * - `PermissionDescriptorCondition`: `{condition: &lt;expression&gt;, subNode: &lt;descriptor&gt;}` grants `subNode` where `condition` holds.
     * - `PermissionDescriptorCompose`: `{permissionDescriptors: [&lt;id&gt;, ...]}` grants other permission sets or roles by ID.
     * - `PermissionDescriptorIfThenElse` and `PermissionDescriptorSelect`, plus the `PermissionExpression*` and `PermissionLiteralExpression*` expressions (And, Or, Not, Equal, HasTag, Tag, Stack, Environment, InsightsAccount, Team, and others).
     * 
     * **When Pulumi Cloud is newer than this provider**, raw descriptors may not work here: the provider checks them against the Pulumi Cloud API version it was built with. It rejects node types it doesn&#39;t recognize and doesn&#39;t send scopes it doesn&#39;t recognize. Until a provider release catches up, use `pulumiservice:api:Role`, which sends its `details` to Pulumi Cloud unchanged.
     * 
     * Note: `__type` keys require pulumi 3.235.0 or later (pulumi/pulumi#22834). Earlier runtimes drop them at the SDK boundary; the Python SDK pins the minimum runtime version automatically.
     * 
     */
    @Export(name="permissions", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output<Map<String,Object>> permissions;

    /**
     * @return The role&#39;s permission descriptor tree.
     * 
     * **Build this with the helper functions.** They construct the tree for you and validate it before anything reaches Pulumi Cloud:
     * - `buildRolePermissions`: start here. It builds a complete role from organization-level access and rules for stacks, environments, and Insights accounts. Each rule grants scopes and/or permission sets on every entity of its type, on one specific entity, or on entities matching tags. Each rule list accepts only scopes and permission sets for its own entity type, so a stack scope can&#39;t end up on an environment rule.
     * - `buildAllowPermissions`: grants scopes with no conditions.
     * - `buildStackScopedPermissions`, `buildEnvironmentScopedPermissions`, and `buildInsightsAccountScopedPermissions`: grant scopes on one specific entity.
     * - `buildComposePermissions`: grants a policy by ID (see below).
     * 
     * Combine helpers by passing their `permissions` outputs to `buildRolePermissions.additionalEntries`. Look up stack IDs with `getStack`, environment IDs with `getEnvironment`, and Insights account IDs with `getInsightsAccount`. To assign the role, use `TeamRoleAssignment` or `OrganizationMember.roleId`.
     * 
     * **Permission sets** (bundles of scopes such as the built-in Stack Write, looked up with `getOrganizationPermissionSet`) can&#39;t be referenced from a role directly: Pulumi Cloud accepts them only in a policy. Build the policy&#39;s permissions with `buildRolePermissions` (`permissionSets`, `organizationPermissionSets`), store them with `pulumiservice:api:Role` (`uxPurpose: policy`), and set this property to `buildComposePermissions` with the policy&#39;s `roleID`. The example below shows both approaches.
     * 
     * **When the helpers can&#39;t express what you need**, write that part as a raw descriptor in the Pulumi Cloud wire format, using the `__type` field to name each node. For example:
     * 
     * Pass it to `buildRolePermissions.additionalEntries`, which keeps the rest of the role on helpers, or assign it to this property directly. The node types are:
     * - `PermissionDescriptorAllow`: `{permissions: [&lt;scope&gt;, ...]}` grants the listed scopes.
     * - `PermissionDescriptorGroup`: `{entries: [&lt;descriptor&gt;, ...]}` grants the union of its entries.
     * - `PermissionDescriptorCondition`: `{condition: &lt;expression&gt;, subNode: &lt;descriptor&gt;}` grants `subNode` where `condition` holds.
     * - `PermissionDescriptorCompose`: `{permissionDescriptors: [&lt;id&gt;, ...]}` grants other permission sets or roles by ID.
     * - `PermissionDescriptorIfThenElse` and `PermissionDescriptorSelect`, plus the `PermissionExpression*` and `PermissionLiteralExpression*` expressions (And, Or, Not, Equal, HasTag, Tag, Stack, Environment, InsightsAccount, Team, and others).
     * 
     * **When Pulumi Cloud is newer than this provider**, raw descriptors may not work here: the provider checks them against the Pulumi Cloud API version it was built with. It rejects node types it doesn&#39;t recognize and doesn&#39;t send scopes it doesn&#39;t recognize. Until a provider release catches up, use `pulumiservice:api:Role`, which sends its `details` to Pulumi Cloud unchanged.
     * 
     * Note: `__type` keys require pulumi 3.235.0 or later (pulumi/pulumi#22834). Earlier runtimes drop them at the SDK boundary; the Python SDK pins the minimum runtime version automatically.
     * 
     */
    public Output<Map<String,Object>> permissions() {
        return this.permissions;
    }
    /**
     * The resource type the role&#39;s permissions apply to. Defaults to `global` (the org-wide role that can be assigned to members and teams). Other valid values: `stack`, `environment`, `insights-account`.
     * 
     */
    @Export(name="resourceType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> resourceType;

    /**
     * @return The resource type the role&#39;s permissions apply to. Defaults to `global` (the org-wide role that can be assigned to members and teams). Other valid values: `stack`, `environment`, `insights-account`.
     * 
     */
    public Output<Optional<String>> resourceType() {
        return Codegen.optional(this.resourceType);
    }
    /**
     * The unique identifier of the custom role.
     * 
     */
    @Export(name="roleId", refs={String.class}, tree="[0]")
    private Output<String> roleId;

    /**
     * @return The unique identifier of the custom role.
     * 
     */
    public Output<String> roleId() {
        return this.roleId;
    }
    /**
     * The service-maintained version number that increments on every update.
     * 
     */
    @Export(name="version", refs={Integer.class}, tree="[0]")
    private Output<Integer> version;

    /**
     * @return The service-maintained version number that increments on every update.
     * 
     */
    public Output<Integer> version() {
        return this.version;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public OrganizationRole(java.lang.String name) {
        this(name, OrganizationRoleArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public OrganizationRole(java.lang.String name, OrganizationRoleArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public OrganizationRole(java.lang.String name, OrganizationRoleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumiservice:index:OrganizationRole", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private OrganizationRole(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumiservice:index:OrganizationRole", name, null, makeResourceOptions(options, id), false);
    }

    private static OrganizationRoleArgs makeArgs(OrganizationRoleArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? OrganizationRoleArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .replaceOnChanges(List.of(
                "organizationName"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static OrganizationRole get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new OrganizationRole(name, id, options);
    }
}
