// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.pulumiservice.TeamRoleAssignmentArgs;
import com.pulumi.pulumiservice.Utilities;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Assigns a custom (fine-grained) role to a Pulumi Cloud team. The Pulumi Cloud API currently supports one role per team; creating a second assignment replaces the first. The team&#39;s organization must already have the custom-roles feature enabled.
 * 
 */
@ResourceType(type="pulumiservice:index:TeamRoleAssignment")
public class TeamRoleAssignment extends com.pulumi.resources.CustomResource {
    /**
     * The Pulumi Cloud organization name.
     * 
     */
    @Export(name="organizationName", refs={String.class}, tree="[0]")
    private Output<String> organizationName;

    /**
     * @return The Pulumi Cloud organization name.
     * 
     */
    public Output<String> organizationName() {
        return this.organizationName;
    }
    /**
     * The ID of the custom role to assign.
     * 
     */
    @Export(name="roleId", refs={String.class}, tree="[0]")
    private Output<String> roleId;

    /**
     * @return The ID of the custom role to assign.
     * 
     */
    public Output<String> roleId() {
        return this.roleId;
    }
    /**
     * The name of the assigned role at the time of last refresh.
     * 
     */
    @Export(name="roleName", refs={String.class}, tree="[0]")
    private Output<String> roleName;

    /**
     * @return The name of the assigned role at the time of last refresh.
     * 
     */
    public Output<String> roleName() {
        return this.roleName;
    }
    /**
     * The team name.
     * 
     */
    @Export(name="teamName", refs={String.class}, tree="[0]")
    private Output<String> teamName;

    /**
     * @return The team name.
     * 
     */
    public Output<String> teamName() {
        return this.teamName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public TeamRoleAssignment(java.lang.String name) {
        this(name, TeamRoleAssignmentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public TeamRoleAssignment(java.lang.String name, TeamRoleAssignmentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public TeamRoleAssignment(java.lang.String name, TeamRoleAssignmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumiservice:index:TeamRoleAssignment", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private TeamRoleAssignment(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pulumiservice:index:TeamRoleAssignment", name, null, makeResourceOptions(options, id), false);
    }

    private static TeamRoleAssignmentArgs makeArgs(TeamRoleAssignmentArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TeamRoleAssignmentArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static TeamRoleAssignment get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new TeamRoleAssignment(name, id, options);
    }
}
