// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ScheduledDeploymentArgs } from "./scheduledDeployment";
export type ScheduledDeployment = import("./scheduledDeployment").ScheduledDeployment;
export const ScheduledDeployment: typeof import("./scheduledDeployment").ScheduledDeployment = null as any;
utilities.lazyLoad(exports, ["ScheduledDeployment"], () => require("./scheduledDeployment"));

export { SettingsArgs } from "./settings";
export type Settings = import("./settings").Settings;
export const Settings: typeof import("./settings").Settings = null as any;
utilities.lazyLoad(exports, ["Settings"], () => require("./settings"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pulumiservice:v2/deployments:ScheduledDeployment":
                return new ScheduledDeployment(name, <any>undefined, { urn })
            case "pulumiservice:v2/deployments:Settings":
                return new Settings(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pulumiservice", "v2/deployments", _module)
