# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities

__all__ = ['TeamEnvironmentPermissionArgs', 'TeamEnvironmentPermission']

@pulumi.input_type
class TeamEnvironmentPermissionArgs:
    def __init__(__self__, *,
                 env_name: pulumi.Input[_builtins.str],
                 organization_name: pulumi.Input[_builtins.str],
                 project_name: pulumi.Input[_builtins.str],
                 team_name: pulumi.Input[_builtins.str],
                 permission: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a TeamEnvironmentPermission resource.

        :param pulumi.Input[_builtins.str] env_name: ESC environment name.
        :param pulumi.Input[_builtins.str] organization_name: Organization name.
        :param pulumi.Input[_builtins.str] project_name: ESC project the environment belongs to.
        :param pulumi.Input[_builtins.str] team_name: Team being granted environment access.
        :param pulumi.Input[_builtins.str] permission: Permission level granted to the team. Omit on delete.
        """
        pulumi.set(__self__, "env_name", env_name)
        pulumi.set(__self__, "organization_name", organization_name)
        pulumi.set(__self__, "project_name", project_name)
        pulumi.set(__self__, "team_name", team_name)
        if permission is not None:
            pulumi.set(__self__, "permission", permission)

    @_builtins.property
    @pulumi.getter(name="envName")
    def env_name(self) -> pulumi.Input[_builtins.str]:
        """
        ESC environment name.
        """
        return pulumi.get(self, "env_name")

    @env_name.setter
    def env_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "env_name", value)

    @_builtins.property
    @pulumi.getter(name="organizationName")
    def organization_name(self) -> pulumi.Input[_builtins.str]:
        """
        Organization name.
        """
        return pulumi.get(self, "organization_name")

    @organization_name.setter
    def organization_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_name", value)

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Input[_builtins.str]:
        """
        ESC project the environment belongs to.
        """
        return pulumi.get(self, "project_name")

    @project_name.setter
    def project_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_name", value)

    @_builtins.property
    @pulumi.getter(name="teamName")
    def team_name(self) -> pulumi.Input[_builtins.str]:
        """
        Team being granted environment access.
        """
        return pulumi.get(self, "team_name")

    @team_name.setter
    def team_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "team_name", value)

    @_builtins.property
    @pulumi.getter
    def permission(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Permission level granted to the team. Omit on delete.
        """
        return pulumi.get(self, "permission")

    @permission.setter
    def permission(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "permission", value)


@pulumi.type_token("pulumiservice:esc/permissions:TeamEnvironmentPermission")
class TeamEnvironmentPermission(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 env_name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization_name: Optional[pulumi.Input[_builtins.str]] = None,
                 permission: Optional[pulumi.Input[_builtins.str]] = None,
                 project_name: Optional[pulumi.Input[_builtins.str]] = None,
                 team_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a TeamEnvironmentPermission resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] env_name: ESC environment name.
        :param pulumi.Input[_builtins.str] organization_name: Organization name.
        :param pulumi.Input[_builtins.str] permission: Permission level granted to the team. Omit on delete.
        :param pulumi.Input[_builtins.str] project_name: ESC project the environment belongs to.
        :param pulumi.Input[_builtins.str] team_name: Team being granted environment access.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TeamEnvironmentPermissionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a TeamEnvironmentPermission resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param TeamEnvironmentPermissionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TeamEnvironmentPermissionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 env_name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization_name: Optional[pulumi.Input[_builtins.str]] = None,
                 permission: Optional[pulumi.Input[_builtins.str]] = None,
                 project_name: Optional[pulumi.Input[_builtins.str]] = None,
                 team_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TeamEnvironmentPermissionArgs.__new__(TeamEnvironmentPermissionArgs)

            if env_name is None and not opts.urn:
                raise TypeError("Missing required property 'env_name'")
            __props__.__dict__["env_name"] = env_name
            if organization_name is None and not opts.urn:
                raise TypeError("Missing required property 'organization_name'")
            __props__.__dict__["organization_name"] = organization_name
            __props__.__dict__["permission"] = permission
            if project_name is None and not opts.urn:
                raise TypeError("Missing required property 'project_name'")
            __props__.__dict__["project_name"] = project_name
            if team_name is None and not opts.urn:
                raise TypeError("Missing required property 'team_name'")
            __props__.__dict__["team_name"] = team_name
        super(TeamEnvironmentPermission, __self__).__init__(
            'pulumiservice:esc/permissions:TeamEnvironmentPermission',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'TeamEnvironmentPermission':
        """
        Get an existing TeamEnvironmentPermission resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = TeamEnvironmentPermissionArgs.__new__(TeamEnvironmentPermissionArgs)

        __props__.__dict__["env_name"] = None
        __props__.__dict__["organization_name"] = None
        __props__.__dict__["permission"] = None
        __props__.__dict__["project_name"] = None
        __props__.__dict__["team_name"] = None
        return TeamEnvironmentPermission(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="envName")
    def env_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        ESC environment name.
        """
        return pulumi.get(self, "env_name")

    @_builtins.property
    @pulumi.getter(name="organizationName")
    def organization_name(self) -> pulumi.Output[_builtins.str]:
        """
        Organization name.
        """
        return pulumi.get(self, "organization_name")

    @_builtins.property
    @pulumi.getter
    def permission(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Permission level granted to the team. Omit on delete.
        """
        return pulumi.get(self, "permission")

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        ESC project the environment belongs to.
        """
        return pulumi.get(self, "project_name")

    @_builtins.property
    @pulumi.getter(name="teamName")
    def team_name(self) -> pulumi.Output[_builtins.str]:
        """
        Team being granted environment access.
        """
        return pulumi.get(self, "team_name")

