// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.api.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class OperationContextAzureOIDCConfiguration {
    /**
     * @return ClientID is the client ID of the federated workload identity.
     * 
     */
    private @Nullable String clientId;
    /**
     * @return SubscriptionID is the subscription ID of the federated workload identity.
     * 
     */
    private @Nullable String subscriptionId;
    /**
     * @return TenantID is the tenant ID of the federated workload identity.
     * 
     */
    private @Nullable String tenantId;

    private OperationContextAzureOIDCConfiguration() {}
    /**
     * @return ClientID is the client ID of the federated workload identity.
     * 
     */
    public Optional<String> clientId() {
        return Optional.ofNullable(this.clientId);
    }
    /**
     * @return SubscriptionID is the subscription ID of the federated workload identity.
     * 
     */
    public Optional<String> subscriptionId() {
        return Optional.ofNullable(this.subscriptionId);
    }
    /**
     * @return TenantID is the tenant ID of the federated workload identity.
     * 
     */
    public Optional<String> tenantId() {
        return Optional.ofNullable(this.tenantId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(OperationContextAzureOIDCConfiguration defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String clientId;
        private @Nullable String subscriptionId;
        private @Nullable String tenantId;
        public Builder() {}
        public Builder(OperationContextAzureOIDCConfiguration defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.clientId = defaults.clientId;
    	      this.subscriptionId = defaults.subscriptionId;
    	      this.tenantId = defaults.tenantId;
        }

        @CustomType.Setter
        public Builder clientId(@Nullable String clientId) {

            this.clientId = clientId;
            return this;
        }
        @CustomType.Setter
        public Builder subscriptionId(@Nullable String subscriptionId) {

            this.subscriptionId = subscriptionId;
            return this;
        }
        @CustomType.Setter
        public Builder tenantId(@Nullable String tenantId) {

            this.tenantId = tenantId;
            return this;
        }
        public OperationContextAzureOIDCConfiguration build() {
            final var _resultValue = new OperationContextAzureOIDCConfiguration();
            _resultValue.clientId = clientId;
            _resultValue.subscriptionId = subscriptionId;
            _resultValue.tenantId = tenantId;
            return _resultValue;
        }
    }
}
