// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.api.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionAnd;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionEnvironment;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionHasTag;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionInsightsAccount;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionNot;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionOr;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionStack;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionTag;
import com.pulumi.pulumiservice.api.outputs.PermissionExpressionTeam;
import com.pulumi.pulumiservice.api.outputs.PermissionLiteralExpressionBool;
import com.pulumi.pulumiservice.api.outputs.PermissionLiteralExpressionEnvironment;
import com.pulumi.pulumiservice.api.outputs.PermissionLiteralExpressionInsightsAccount;
import com.pulumi.pulumiservice.api.outputs.PermissionLiteralExpressionNumber;
import com.pulumi.pulumiservice.api.outputs.PermissionLiteralExpressionStack;
import com.pulumi.pulumiservice.api.outputs.PermissionLiteralExpressionString;
import com.pulumi.pulumiservice.api.outputs.PermissionLiteralExpressionTeam;
import java.lang.Object;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PermissionExpressionEqual {
    /**
     * @return Expected value is &#39;PermissionExpressionEqual&#39;.
     * 
     */
    private String __type;
    /**
     * @return The left operand of the equality comparison.
     * 
     * Valid `__type` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
     * 
     */
    private @Nullable Object left;
    /**
     * @return The right operand of the equality comparison.
     * 
     * Valid `__type` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
     * 
     */
    private @Nullable Object right;

    private PermissionExpressionEqual() {}
    /**
     * @return Expected value is &#39;PermissionExpressionEqual&#39;.
     * 
     */
    public String __type() {
        return this.__type;
    }
    /**
     * @return The left operand of the equality comparison.
     * 
     * Valid `__type` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
     * 
     */
    public Optional<Object> left() {
        return Optional.ofNullable(this.left);
    }
    /**
     * @return The right operand of the equality comparison.
     * 
     * Valid `__type` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
     * 
     */
    public Optional<Object> right() {
        return Optional.ofNullable(this.right);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PermissionExpressionEqual defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String __type;
        private @Nullable Object left;
        private @Nullable Object right;
        public Builder() {}
        public Builder(PermissionExpressionEqual defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.__type = defaults.__type;
    	      this.left = defaults.left;
    	      this.right = defaults.right;
        }

        @CustomType.Setter
        public Builder __type(String __type) {
            if (__type == null) {
              throw new MissingRequiredPropertyException("PermissionExpressionEqual", "__type");
            }
            this.__type = __type;
            return this;
        }
        @CustomType.Setter
        public Builder left(@Nullable Object left) {

            this.left = left;
            return this;
        }
        @CustomType.Setter
        public Builder right(@Nullable Object right) {

            this.right = right;
            return this;
        }
        public PermissionExpressionEqual build() {
            final var _resultValue = new PermissionExpressionEqual();
            _resultValue.__type = __type;
            _resultValue.left = left;
            _resultValue.right = right;
            return _resultValue;
        }
    }
}
