// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.stacks_tags;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;


public final class TagsArgs extends com.pulumi.resources.ResourceArgs {

    public static final TagsArgs Empty = new TagsArgs();

    /**
     * Organization name.
     * 
     */
    @Import(name="organization", required=true)
    private Output<String> organization;

    /**
     * @return Organization name.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }

    /**
     * Project name.
     * 
     */
    @Import(name="project", required=true)
    private Output<String> project;

    /**
     * @return Project name.
     * 
     */
    public Output<String> project() {
        return this.project;
    }

    /**
     * Stack name.
     * 
     */
    @Import(name="stack", required=true)
    private Output<String> stack;

    /**
     * @return Stack name.
     * 
     */
    public Output<String> stack() {
        return this.stack;
    }

    /**
     * Tag name → tag value map managed by this resource.
     * 
     */
    @Import(name="tags", required=true)
    private Output<Map<String,String>> tags;

    /**
     * @return Tag name → tag value map managed by this resource.
     * 
     */
    public Output<Map<String,String>> tags() {
        return this.tags;
    }

    private TagsArgs() {}

    private TagsArgs(TagsArgs $) {
        this.organization = $.organization;
        this.project = $.project;
        this.stack = $.stack;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TagsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TagsArgs $;

        public Builder() {
            $ = new TagsArgs();
        }

        public Builder(TagsArgs defaults) {
            $ = new TagsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param organization Organization name.
         * 
         * @return builder
         * 
         */
        public Builder organization(Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization Organization name.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param project Project name.
         * 
         * @return builder
         * 
         */
        public Builder project(Output<String> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project Project name.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            return project(Output.of(project));
        }

        /**
         * @param stack Stack name.
         * 
         * @return builder
         * 
         */
        public Builder stack(Output<String> stack) {
            $.stack = stack;
            return this;
        }

        /**
         * @param stack Stack name.
         * 
         * @return builder
         * 
         */
        public Builder stack(String stack) {
            return stack(Output.of(stack));
        }

        /**
         * @param tags Tag name → tag value map managed by this resource.
         * 
         * @return builder
         * 
         */
        public Builder tags(Output<Map<String,String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags Tag name → tag value map managed by this resource.
         * 
         * @return builder
         * 
         */
        public Builder tags(Map<String,String> tags) {
            return tags(Output.of(tags));
        }

        public TagsArgs build() {
            if ($.organization == null) {
                throw new MissingRequiredPropertyException("TagsArgs", "organization");
            }
            if ($.project == null) {
                throw new MissingRequiredPropertyException("TagsArgs", "project");
            }
            if ($.stack == null) {
                throw new MissingRequiredPropertyException("TagsArgs", "stack");
            }
            if ($.tags == null) {
                throw new MissingRequiredPropertyException("TagsArgs", "tags");
            }
            return $;
        }
    }

}
