// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * The executor context defines information about the executor where the deployment is executed. If unspecified, the default &#39;pulumi/pulumi&#39; image is used.
 * 
 */
public final class DeploymentSettingsExecutorContextArgs extends com.pulumi.resources.ResourceArgs {

    public static final DeploymentSettingsExecutorContextArgs Empty = new DeploymentSettingsExecutorContextArgs();

    /**
     * Allows overriding the default executor image with a custom image. E.g. &#39;pulumi/pulumi-nodejs:latest&#39;
     * 
     */
    @Import(name="executorImage")
    private @Nullable Output<String> executorImage;

    /**
     * @return Allows overriding the default executor image with a custom image. E.g. &#39;pulumi/pulumi-nodejs:latest&#39;
     * 
     */
    public Optional<Output<String>> executorImage() {
        return Optional.ofNullable(this.executorImage);
    }

    /**
     * Override the default root path (/) used by the deployment executor. This can be useful when running with non-root users (e.g., set to /tmp ).
     * 
     */
    @Import(name="executorRootPath")
    private @Nullable Output<String> executorRootPath;

    /**
     * @return Override the default root path (/) used by the deployment executor. This can be useful when running with non-root users (e.g., set to /tmp ).
     * 
     */
    public Optional<Output<String>> executorRootPath() {
        return Optional.ofNullable(this.executorRootPath);
    }

    private DeploymentSettingsExecutorContextArgs() {}

    private DeploymentSettingsExecutorContextArgs(DeploymentSettingsExecutorContextArgs $) {
        this.executorImage = $.executorImage;
        this.executorRootPath = $.executorRootPath;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DeploymentSettingsExecutorContextArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DeploymentSettingsExecutorContextArgs $;

        public Builder() {
            $ = new DeploymentSettingsExecutorContextArgs();
        }

        public Builder(DeploymentSettingsExecutorContextArgs defaults) {
            $ = new DeploymentSettingsExecutorContextArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param executorImage Allows overriding the default executor image with a custom image. E.g. &#39;pulumi/pulumi-nodejs:latest&#39;
         * 
         * @return builder
         * 
         */
        public Builder executorImage(@Nullable Output<String> executorImage) {
            $.executorImage = executorImage;
            return this;
        }

        /**
         * @param executorImage Allows overriding the default executor image with a custom image. E.g. &#39;pulumi/pulumi-nodejs:latest&#39;
         * 
         * @return builder
         * 
         */
        public Builder executorImage(String executorImage) {
            return executorImage(Output.of(executorImage));
        }

        /**
         * @param executorRootPath Override the default root path (/) used by the deployment executor. This can be useful when running with non-root users (e.g., set to /tmp ).
         * 
         * @return builder
         * 
         */
        public Builder executorRootPath(@Nullable Output<String> executorRootPath) {
            $.executorRootPath = executorRootPath;
            return this;
        }

        /**
         * @param executorRootPath Override the default root path (/) used by the deployment executor. This can be useful when running with non-root users (e.g., set to /tmp ).
         * 
         * @return builder
         * 
         */
        public Builder executorRootPath(String executorRootPath) {
            return executorRootPath(Output.of(executorRootPath));
        }

        public DeploymentSettingsExecutorContextArgs build() {
            return $;
        }
    }

}
