// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.V2
{
    /// <summary>
    /// Creates a new webhook for an organization to notify external services when events occur. Webhooks can be configured to fire on stack events (created, deleted, update succeeded/failed), deployment events (queued, started, succeeded, failed), drift detection events, and policy violation events (mandatory, advisory).
    /// 
    /// The `format` field accepts: `raw` (default), `slack`, `ms_teams`, or `pulumi_deployments`.
    /// 
    /// The `filters` field accepts a list of event types to subscribe to. See the [webhook event filtering documentation](https://www.pulumi.com/docs/pulumi-cloud/webhooks/#event-filtering) for available filters.
    /// 
    /// The optional `secret` field sets the HMAC key for signature verification via the `Pulumi-Webhook-Signature` header. See the [webhook headers documentation](https://www.pulumi.com/docs/pulumi-cloud/webhooks/#headers) for details.
    /// </summary>
    [PulumiServiceResourceType("pulumiservice:v2:OrganizationWebhook")]
    public partial class OrganizationWebhook : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether the webhook is active and will receive deliveries.
        /// </summary>
        [Output("active")]
        public Output<bool> Active { get; private set; } = null!;

        /// <summary>
        /// The human-readable display name shown in the UI.
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// The environment name. Set when the webhook is scoped to a specific environment.
        /// </summary>
        [Output("envName")]
        public Output<string?> EnvName { get; private set; } = null!;

        /// <summary>
        /// Specific event types this webhook subscribes to. If empty, all events are delivered.
        /// </summary>
        [Output("filters")]
        public Output<ImmutableArray<string>> Filters { get; private set; } = null!;

        /// <summary>
        /// The format of the webhook payload (e.g., 'raw', 'slack', 'ms_teams').
        /// </summary>
        [Output("format")]
        public Output<string?> Format { get; private set; } = null!;

        /// <summary>
        /// Event groups this webhook subscribes to (e.g., 'stacks', 'deployments').
        /// </summary>
        [Output("groups")]
        public Output<ImmutableArray<string>> Groups { get; private set; } = null!;

        /// <summary>
        /// HasSecret is true if the webhook has a secret. This is used to determine whether
        /// to show that there is a secret in the UI.
        /// </summary>
        [Output("hasSecret")]
        public Output<bool> HasSecret { get; private set; } = null!;

        /// <summary>
        /// The unique identifier name for the webhook within its scope.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The organization that owns this webhook.
        /// </summary>
        [Output("organizationName")]
        public Output<string> OrganizationName { get; private set; } = null!;

        /// <summary>
        /// The URL to which webhook payloads are delivered.
        /// </summary>
        [Output("payloadUrl")]
        public Output<string> PayloadUrl { get; private set; } = null!;

        /// <summary>
        /// The project name. Set when the webhook is scoped to a specific stack.
        /// </summary>
        [Output("projectName")]
        public Output<string?> ProjectName { get; private set; } = null!;

        /// <summary>
        /// Secret will be omitted when returned from the service.
        /// </summary>
        [Output("secret")]
        public Output<string?> Secret { get; private set; } = null!;

        /// <summary>
        /// SecretCiphertext is the ciphertext value of the webhook's secret.
        /// It's used to check whether the secret was changed by the PSP
        /// </summary>
        [Output("secretCiphertext")]
        public Output<string> SecretCiphertext { get; private set; } = null!;

        /// <summary>
        /// The stack name. Set when the webhook is scoped to a specific stack.
        /// </summary>
        [Output("stackName")]
        public Output<string?> StackName { get; private set; } = null!;


        /// <summary>
        /// Create a OrganizationWebhook resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OrganizationWebhook(string name, OrganizationWebhookArgs args, CustomResourceOptions? options = null)
            : base("pulumiservice:v2:OrganizationWebhook", name, args ?? new OrganizationWebhookArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OrganizationWebhook(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pulumiservice:v2:OrganizationWebhook", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "hasSecret",
                    "secret",
                    "secretCiphertext",
                },
                ReplaceOnChanges =
                {
                    "name",
                    "organizationName",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OrganizationWebhook resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OrganizationWebhook Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new OrganizationWebhook(name, id, options);
        }
    }

    public sealed class OrganizationWebhookArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the webhook is active and will receive deliveries.
        /// </summary>
        [Input("active", required: true)]
        public Input<bool> Active { get; set; } = null!;

        /// <summary>
        /// The human-readable display name shown in the UI.
        /// </summary>
        [Input("displayName", required: true)]
        public Input<string> DisplayName { get; set; } = null!;

        /// <summary>
        /// The environment name. Set when the webhook is scoped to a specific environment.
        /// </summary>
        [Input("envName")]
        public Input<string>? EnvName { get; set; }

        [Input("filters")]
        private InputList<string>? _filters;

        /// <summary>
        /// Specific event types this webhook subscribes to. If empty, all events are delivered.
        /// </summary>
        public InputList<string> Filters
        {
            get => _filters ?? (_filters = new InputList<string>());
            set => _filters = value;
        }

        /// <summary>
        /// The format of the webhook payload (e.g., 'raw', 'slack', 'ms_teams').
        /// </summary>
        [Input("format")]
        public Input<string>? Format { get; set; }

        [Input("groups")]
        private InputList<string>? _groups;

        /// <summary>
        /// Event groups this webhook subscribes to (e.g., 'stacks', 'deployments').
        /// </summary>
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        /// <summary>
        /// The unique identifier name for the webhook within its scope.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The organization that owns this webhook.
        /// </summary>
        [Input("organizationName", required: true)]
        public Input<string> OrganizationName { get; set; } = null!;

        /// <summary>
        /// The URL to which webhook payloads are delivered.
        /// </summary>
        [Input("payloadUrl", required: true)]
        public Input<string> PayloadUrl { get; set; } = null!;

        /// <summary>
        /// The project name. Set when the webhook is scoped to a specific stack.
        /// </summary>
        [Input("projectName")]
        public Input<string>? ProjectName { get; set; }

        /// <summary>
        /// Secret will be omitted when returned from the service.
        /// </summary>
        [Input("secret")]
        public Input<string>? Secret { get; set; }

        /// <summary>
        /// The stack name. Set when the webhook is scoped to a specific stack.
        /// </summary>
        [Input("stackName")]
        public Input<string>? StackName { get; set; }

        public OrganizationWebhookArgs()
        {
        }
        public static new OrganizationWebhookArgs Empty => new OrganizationWebhookArgs();
    }
}
