// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.api_integrations.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CustomVCSRepositoryProperties {
    /**
     * @return Human-readable display name for the repository. If not provided, the name is used for display purposes.
     * 
     */
    private @Nullable String displayName;
    /**
     * @return Repository name or path, joined with the integration&#39;s base URL to form the clone URL (e.g. &#39;myrepo&#39; or &#39;subgroup/myrepo&#39;)
     * 
     */
    private String name;

    private CustomVCSRepositoryProperties() {}
    /**
     * @return Human-readable display name for the repository. If not provided, the name is used for display purposes.
     * 
     */
    public Optional<String> displayName() {
        return Optional.ofNullable(this.displayName);
    }
    /**
     * @return Repository name or path, joined with the integration&#39;s base URL to form the clone URL (e.g. &#39;myrepo&#39; or &#39;subgroup/myrepo&#39;)
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CustomVCSRepositoryProperties defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String displayName;
        private String name;
        public Builder() {}
        public Builder(CustomVCSRepositoryProperties defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.displayName = defaults.displayName;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder displayName(@Nullable String displayName) {

            this.displayName = displayName;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("CustomVCSRepositoryProperties", "name");
            }
            this.name = name;
            return this;
        }
        public CustomVCSRepositoryProperties build() {
            final var _resultValue = new CustomVCSRepositoryProperties();
            _resultValue.displayName = displayName;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
