# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'AppMessage',
    'AppPolicyPackMetadata',
    'AppPulumiStackReference',
    'ApprovalRuleEligibilityOutputPermission',
    'ApprovalRuleEligibilityOutputTeam',
    'ApprovalRuleEligibilityOutputUser',
    'AuditLogExportResult',
    'AuditLogsExportS3Config',
    'ChangeGateApprovalRuleOutput',
    'ChangeGateTargetOutput',
    'FGARole',
    'JobRun',
    'MemberLinks',
    'PermissionDescriptorAllow',
    'PermissionDescriptorCompose',
    'PermissionDescriptorCondition',
    'PermissionDescriptorGroup',
    'PermissionDescriptorIfThenElse',
    'PermissionDescriptorSelect',
    'PermissionExpressionAnd',
    'PermissionExpressionEnvironment',
    'PermissionExpressionEqual',
    'PermissionExpressionHasTag',
    'PermissionExpressionInsightsAccount',
    'PermissionExpressionNot',
    'PermissionExpressionOr',
    'PermissionExpressionStack',
    'PermissionExpressionTag',
    'PermissionExpressionTeam',
    'PermissionLiteralExpressionBool',
    'PermissionLiteralExpressionEnvironment',
    'PermissionLiteralExpressionInsightsAccount',
    'PermissionLiteralExpressionNumber',
    'PermissionLiteralExpressionStack',
    'PermissionLiteralExpressionString',
    'PermissionLiteralExpressionTeam',
    'PermissionSelectvalue',
    'RbacPermissionConstraints',
    'ScanStatus',
    'StepRun',
    'TargetEntityEnvironment',
    'TemplateDestination',
    'UserInfo',
]

@pulumi.output_type
class AppMessage(dict):
    """
    Message is a message from the backend to be displayed to the user.
    """
    def __init__(__self__, *,
                 message: _builtins.str,
                 severity: Optional[_builtins.str] = None):
        """
        Message is a message from the backend to be displayed to the user.

        :param _builtins.str message: Message is the message to display to the user.
        :param _builtins.str severity: Severity is the severity of the message.
        """
        pulumi.set(__self__, "message", message)
        if severity is not None:
            pulumi.set(__self__, "severity", severity)

    @_builtins.property
    @pulumi.getter
    def message(self) -> _builtins.str:
        """
        Message is the message to display to the user.
        """
        return pulumi.get(self, "message")

    @_builtins.property
    @pulumi.getter
    def severity(self) -> Optional[_builtins.str]:
        """
        Severity is the severity of the message.
        """
        return pulumi.get(self, "severity")


@pulumi.output_type
class AppPolicyPackMetadata(dict):
    """
    PolicyPackMetadata is the metadata of a Policy Pack.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "displayName":
            suggest = "display_name"
        elif key == "versionTag":
            suggest = "version_tag"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AppPolicyPackMetadata. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AppPolicyPackMetadata.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AppPolicyPackMetadata.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 display_name: _builtins.str,
                 name: _builtins.str,
                 version: _builtins.int,
                 version_tag: _builtins.str,
                 config: Optional[Mapping[str, Mapping[str, Any]]] = None,
                 environments: Optional[Sequence[_builtins.str]] = None):
        """
        PolicyPackMetadata is the metadata of a Policy Pack.

        :param _builtins.str display_name: The display name
        :param _builtins.str name: The name
        :param _builtins.int version: The version number
        :param _builtins.str version_tag: The version tag
        :param Mapping[str, Mapping[str, Any]] config: The configuration that is to be passed to the Policy Pack. This
               map ties Policies with their configuration.
        :param Sequence[_builtins.str] environments: References to ESC environments to use for this policy pack.
        """
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "version", version)
        pulumi.set(__self__, "version_tag", version_tag)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if environments is not None:
            pulumi.set(__self__, "environments", environments)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> _builtins.str:
        """
        The display name
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.int:
        """
        The version number
        """
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter(name="versionTag")
    def version_tag(self) -> _builtins.str:
        """
        The version tag
        """
        return pulumi.get(self, "version_tag")

    @_builtins.property
    @pulumi.getter
    def config(self) -> Optional[Mapping[str, Mapping[str, Any]]]:
        """
        The configuration that is to be passed to the Policy Pack. This
        map ties Policies with their configuration.
        """
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter
    def environments(self) -> Optional[Sequence[_builtins.str]]:
        """
        References to ESC environments to use for this policy pack.
        """
        return pulumi.get(self, "environments")


@pulumi.output_type
class AppPulumiStackReference(dict):
    """
    PulumiStackReference contains the StackName and ProjectName of the stack.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "routingProject":
            suggest = "routing_project"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AppPulumiStackReference. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AppPulumiStackReference.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AppPulumiStackReference.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 name: _builtins.str,
                 routing_project: _builtins.str):
        """
        PulumiStackReference contains the StackName and ProjectName of the stack.

        :param _builtins.str name: The name
        :param _builtins.str routing_project: The routing project
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "routing_project", routing_project)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="routingProject")
    def routing_project(self) -> _builtins.str:
        """
        The routing project
        """
        return pulumi.get(self, "routing_project")


@pulumi.output_type
class ApprovalRuleEligibilityOutputPermission(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "eligibilityType":
            suggest = "eligibility_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ApprovalRuleEligibilityOutputPermission. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ApprovalRuleEligibilityOutputPermission.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ApprovalRuleEligibilityOutputPermission.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 eligibility_type: _builtins.str,
                 permission: _builtins.str):
        """
        :param _builtins.str eligibility_type: Expected value is 'has_permission_on_target'.
        :param _builtins.str permission: Required permission
        """
        pulumi.set(__self__, "eligibility_type", 'has_permission_on_target')
        pulumi.set(__self__, "permission", permission)

    @_builtins.property
    @pulumi.getter(name="eligibilityType")
    def eligibility_type(self) -> _builtins.str:
        """
        Expected value is 'has_permission_on_target'.
        """
        return pulumi.get(self, "eligibility_type")

    @_builtins.property
    @pulumi.getter
    def permission(self) -> _builtins.str:
        """
        Required permission
        """
        return pulumi.get(self, "permission")


@pulumi.output_type
class ApprovalRuleEligibilityOutputTeam(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "displayName":
            suggest = "display_name"
        elif key == "eligibilityType":
            suggest = "eligibility_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ApprovalRuleEligibilityOutputTeam. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ApprovalRuleEligibilityOutputTeam.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ApprovalRuleEligibilityOutputTeam.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 display_name: _builtins.str,
                 eligibility_type: _builtins.str,
                 name: _builtins.str):
        """
        :param _builtins.str display_name: Display name
        :param _builtins.str eligibility_type: Expected value is 'team_member'.
        :param _builtins.str name: Team name
        """
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "eligibility_type", 'team_member')
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> _builtins.str:
        """
        Display name
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter(name="eligibilityType")
    def eligibility_type(self) -> _builtins.str:
        """
        Expected value is 'team_member'.
        """
        return pulumi.get(self, "eligibility_type")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Team name
        """
        return pulumi.get(self, "name")


@pulumi.output_type
class ApprovalRuleEligibilityOutputUser(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "eligibilityType":
            suggest = "eligibility_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ApprovalRuleEligibilityOutputUser. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ApprovalRuleEligibilityOutputUser.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ApprovalRuleEligibilityOutputUser.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 eligibility_type: _builtins.str,
                 user: 'outputs.UserInfo'):
        """
        :param _builtins.str eligibility_type: Expected value is 'specific_user'.
        :param 'UserInfo' user: The user
        """
        pulumi.set(__self__, "eligibility_type", 'specific_user')
        pulumi.set(__self__, "user", user)

    @_builtins.property
    @pulumi.getter(name="eligibilityType")
    def eligibility_type(self) -> _builtins.str:
        """
        Expected value is 'specific_user'.
        """
        return pulumi.get(self, "eligibility_type")

    @_builtins.property
    @pulumi.getter
    def user(self) -> 'outputs.UserInfo':
        """
        The user
        """
        return pulumi.get(self, "user")


@pulumi.output_type
class AuditLogExportResult(dict):
    """
    AuditLogExportResult is the result of an audit log export or attempt to test access.
    """
    def __init__(__self__, *,
                 message: _builtins.str,
                 timestamp: _builtins.int):
        """
        AuditLogExportResult is the result of an audit log export or attempt to test access.

        :param _builtins.str message: If the last result was successful, message will be "".
               Any other value is a user-facing error message.
        :param _builtins.int timestamp: The timestamp
        """
        pulumi.set(__self__, "message", message)
        pulumi.set(__self__, "timestamp", timestamp)

    @_builtins.property
    @pulumi.getter
    def message(self) -> _builtins.str:
        """
        If the last result was successful, message will be "".
        Any other value is a user-facing error message.
        """
        return pulumi.get(self, "message")

    @_builtins.property
    @pulumi.getter
    def timestamp(self) -> _builtins.int:
        """
        The timestamp
        """
        return pulumi.get(self, "timestamp")


@pulumi.output_type
class AuditLogsExportS3Config(dict):
    """
    AuditLogsExportS3Config describes how a Pulumi organization's audit log data can be exported to S3.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "iamRoleArn":
            suggest = "iam_role_arn"
        elif key == "s3BucketName":
            suggest = "s3_bucket_name"
        elif key == "s3PathPrefix":
            suggest = "s3_path_prefix"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AuditLogsExportS3Config. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AuditLogsExportS3Config.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AuditLogsExportS3Config.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 iam_role_arn: _builtins.str,
                 s3_bucket_name: _builtins.str,
                 s3_path_prefix: Optional[_builtins.str] = None):
        """
        AuditLogsExportS3Config describes how a Pulumi organization's audit log data can be exported to S3.

        :param _builtins.str iam_role_arn: ARN of the IAM role that Pulumi will assume to write to the S3 bucket.
        :param _builtins.str s3_bucket_name: Name of the S3 bucket to export audit logs to.
        :param _builtins.str s3_path_prefix: Optional path prefix within the S3 bucket for exported log files.
        """
        pulumi.set(__self__, "iam_role_arn", iam_role_arn)
        pulumi.set(__self__, "s3_bucket_name", s3_bucket_name)
        if s3_path_prefix is not None:
            pulumi.set(__self__, "s3_path_prefix", s3_path_prefix)

    @_builtins.property
    @pulumi.getter(name="iamRoleArn")
    def iam_role_arn(self) -> _builtins.str:
        """
        ARN of the IAM role that Pulumi will assume to write to the S3 bucket.
        """
        return pulumi.get(self, "iam_role_arn")

    @_builtins.property
    @pulumi.getter(name="s3BucketName")
    def s3_bucket_name(self) -> _builtins.str:
        """
        Name of the S3 bucket to export audit logs to.
        """
        return pulumi.get(self, "s3_bucket_name")

    @_builtins.property
    @pulumi.getter(name="s3PathPrefix")
    def s3_path_prefix(self) -> Optional[_builtins.str]:
        """
        Optional path prefix within the S3 bucket for exported log files.
        """
        return pulumi.get(self, "s3_path_prefix")


@pulumi.output_type
class ChangeGateApprovalRuleOutput(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "allowSelfApproval":
            suggest = "allow_self_approval"
        elif key == "eligibleApprovers":
            suggest = "eligible_approvers"
        elif key == "numApprovalsRequired":
            suggest = "num_approvals_required"
        elif key == "requireReapprovalOnChange":
            suggest = "require_reapproval_on_change"
        elif key == "ruleType":
            suggest = "rule_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ChangeGateApprovalRuleOutput. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ChangeGateApprovalRuleOutput.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ChangeGateApprovalRuleOutput.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 allow_self_approval: _builtins.bool,
                 eligible_approvers: Sequence[Any],
                 num_approvals_required: _builtins.int,
                 require_reapproval_on_change: _builtins.bool,
                 rule_type: _builtins.str):
        """
        :param _builtins.bool allow_self_approval: Whether self approval is allowed
        :param Sequence[Union['ApprovalRuleEligibilityOutputPermission', 'ApprovalRuleEligibilityOutputUser', 'ApprovalRuleEligibilityOutputTeam']] eligible_approvers: List of eligible approvers
               
               Valid `eligibilityType` values: has_permission_on_target, specific_user, team_member.
        :param _builtins.int num_approvals_required: Number of approvals required
        :param _builtins.bool require_reapproval_on_change: Whether reapproval is required when the change request is modified
        :param _builtins.str rule_type: Expected value is 'approval_required'.
        """
        pulumi.set(__self__, "allow_self_approval", allow_self_approval)
        pulumi.set(__self__, "eligible_approvers", eligible_approvers)
        pulumi.set(__self__, "num_approvals_required", num_approvals_required)
        pulumi.set(__self__, "require_reapproval_on_change", require_reapproval_on_change)
        pulumi.set(__self__, "rule_type", 'approval_required')

    @_builtins.property
    @pulumi.getter(name="allowSelfApproval")
    def allow_self_approval(self) -> _builtins.bool:
        """
        Whether self approval is allowed
        """
        return pulumi.get(self, "allow_self_approval")

    @_builtins.property
    @pulumi.getter(name="eligibleApprovers")
    def eligible_approvers(self) -> Sequence[Any]:
        """
        List of eligible approvers

        Valid `eligibilityType` values: has_permission_on_target, specific_user, team_member.
        """
        return pulumi.get(self, "eligible_approvers")

    @_builtins.property
    @pulumi.getter(name="numApprovalsRequired")
    def num_approvals_required(self) -> _builtins.int:
        """
        Number of approvals required
        """
        return pulumi.get(self, "num_approvals_required")

    @_builtins.property
    @pulumi.getter(name="requireReapprovalOnChange")
    def require_reapproval_on_change(self) -> _builtins.bool:
        """
        Whether reapproval is required when the change request is modified
        """
        return pulumi.get(self, "require_reapproval_on_change")

    @_builtins.property
    @pulumi.getter(name="ruleType")
    def rule_type(self) -> _builtins.str:
        """
        Expected value is 'approval_required'.
        """
        return pulumi.get(self, "rule_type")


@pulumi.output_type
class ChangeGateTargetOutput(dict):
    """
    Output representation of change gate target - contains full details for API responses
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "actionTypes":
            suggest = "action_types"
        elif key == "entityType":
            suggest = "entity_type"
        elif key == "entityInfo":
            suggest = "entity_info"
        elif key == "qualifiedName":
            suggest = "qualified_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ChangeGateTargetOutput. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ChangeGateTargetOutput.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ChangeGateTargetOutput.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 action_types: Sequence[_builtins.str],
                 entity_type: _builtins.str,
                 entity_info: Optional['outputs.TargetEntityEnvironment'] = None,
                 qualified_name: Optional[_builtins.str] = None):
        """
        Output representation of change gate target - contains full details for API responses

        :param Sequence[_builtins.str] action_types: The action types this gate targets
        :param _builtins.str entity_type: The entity type this gate targets
        :param 'TargetEntityEnvironment' entity_info: Populated details about the target entity
        :param _builtins.str qualified_name: The qualified name of the entity this gate targets (e.g., 'project/env')
        """
        pulumi.set(__self__, "action_types", action_types)
        pulumi.set(__self__, "entity_type", entity_type)
        if entity_info is not None:
            pulumi.set(__self__, "entity_info", entity_info)
        if qualified_name is not None:
            pulumi.set(__self__, "qualified_name", qualified_name)

    @_builtins.property
    @pulumi.getter(name="actionTypes")
    def action_types(self) -> Sequence[_builtins.str]:
        """
        The action types this gate targets
        """
        return pulumi.get(self, "action_types")

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> _builtins.str:
        """
        The entity type this gate targets
        """
        return pulumi.get(self, "entity_type")

    @_builtins.property
    @pulumi.getter(name="entityInfo")
    def entity_info(self) -> Optional['outputs.TargetEntityEnvironment']:
        """
        Populated details about the target entity
        """
        return pulumi.get(self, "entity_info")

    @_builtins.property
    @pulumi.getter(name="qualifiedName")
    def qualified_name(self) -> Optional[_builtins.str]:
        """
        The qualified name of the entity this gate targets (e.g., 'project/env')
        """
        return pulumi.get(self, "qualified_name")


@pulumi.output_type
class FGARole(dict):
    """
    A role assigned to an organization member, identified by ID and name. The role may be a built-in role or a custom role.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "modifiedAt":
            suggest = "modified_at"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in FGARole. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        FGARole.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        FGARole.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 id: _builtins.str,
                 modified_at: _builtins.str,
                 name: _builtins.str):
        """
        A role assigned to an organization member, identified by ID and name. The role may be a built-in role or a custom role.

        :param _builtins.str id: The unique identifier of the role.
        :param _builtins.str modified_at: The timestamp when the role was last modified.
        :param _builtins.str name: The name of the role.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "modified_at", modified_at)
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the role.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="modifiedAt")
    def modified_at(self) -> _builtins.str:
        """
        The timestamp when the role was last modified.
        """
        return pulumi.get(self, "modified_at")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the role.
        """
        return pulumi.get(self, "name")


@pulumi.output_type
class JobRun(dict):
    """
    JobRun contains information about a job run.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "lastUpdated":
            suggest = "last_updated"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in JobRun. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        JobRun.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        JobRun.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 status: _builtins.str,
                 steps: Sequence['outputs.StepRun'],
                 timeout: _builtins.int,
                 last_updated: Optional[_builtins.str] = None,
                 started: Optional[_builtins.str] = None,
                 worker: Optional[Mapping[str, Any]] = None):
        """
        JobRun contains information about a job run.

        :param _builtins.str status: The current status of the job run
        :param Sequence['StepRun'] steps: The list of step runs within this job
        :param _builtins.int timeout: The timeout duration for the job in nanoseconds (Go time.Duration).
        :param _builtins.str last_updated: When the job was last updated
        :param _builtins.str started: When the job started running
        :param Mapping[str, Any] worker: Information about the worker executing this job
        """
        pulumi.set(__self__, "status", status)
        pulumi.set(__self__, "steps", steps)
        pulumi.set(__self__, "timeout", timeout)
        if last_updated is not None:
            pulumi.set(__self__, "last_updated", last_updated)
        if started is not None:
            pulumi.set(__self__, "started", started)
        if worker is not None:
            pulumi.set(__self__, "worker", worker)

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        The current status of the job run
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def steps(self) -> Sequence['outputs.StepRun']:
        """
        The list of step runs within this job
        """
        return pulumi.get(self, "steps")

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> _builtins.int:
        """
        The timeout duration for the job in nanoseconds (Go time.Duration).
        """
        return pulumi.get(self, "timeout")

    @_builtins.property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> Optional[_builtins.str]:
        """
        When the job was last updated
        """
        return pulumi.get(self, "last_updated")

    @_builtins.property
    @pulumi.getter
    def started(self) -> Optional[_builtins.str]:
        """
        When the job started running
        """
        return pulumi.get(self, "started")

    @_builtins.property
    @pulumi.getter
    def worker(self) -> Optional[Mapping[str, Any]]:
        """
        Information about the worker executing this job
        """
        return pulumi.get(self, "worker")


@pulumi.output_type
class MemberLinks(dict):
    """
    MemberLinks contains hypermedia links related to an organization member.
    """
    def __init__(__self__, *,
                 self: Optional[_builtins.str] = None):
        """
        MemberLinks contains hypermedia links related to an organization member.

        :param _builtins.str self: A self-referencing hypermedia link (URL) to this member resource.
        """
        if self is not None:
            pulumi.set(__self__, "self", self)

    @_builtins.property
    @pulumi.getter
    def self(self) -> Optional[_builtins.str]:
        """
        A self-referencing hypermedia link (URL) to this member resource.
        """
        return pulumi.get(self, "self")


@pulumi.output_type
class PermissionDescriptorAllow(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 constraints: Optional['outputs.RbacPermissionConstraints'] = None,
                 permissions: Optional[Sequence[_builtins.str]] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionDescriptorAllow'.
        :param 'RbacPermissionConstraints' constraints: Optional contextual constraints for the permissions
        :param Sequence[_builtins.str] permissions: List of permissions to allow
        """
        pulumi.set(__self__, "type__", 'PermissionDescriptorAllow')
        if constraints is not None:
            pulumi.set(__self__, "constraints", constraints)
        if permissions is not None:
            pulumi.set(__self__, "permissions", permissions)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionDescriptorAllow'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def constraints(self) -> Optional['outputs.RbacPermissionConstraints']:
        """
        Optional contextual constraints for the permissions
        """
        return pulumi.get(self, "constraints")

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of permissions to allow
        """
        return pulumi.get(self, "permissions")


@pulumi.output_type
class PermissionDescriptorCompose(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "permissionDescriptors":
            suggest = "permission_descriptors"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PermissionDescriptorCompose. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PermissionDescriptorCompose.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PermissionDescriptorCompose.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 type__: _builtins.str,
                 permission_descriptors: Optional[Sequence[_builtins.str]] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionDescriptorCompose'.
        :param Sequence[_builtins.str] permission_descriptors: References to other descriptors to include in the tree
        """
        pulumi.set(__self__, "type__", 'PermissionDescriptorCompose')
        if permission_descriptors is not None:
            pulumi.set(__self__, "permission_descriptors", permission_descriptors)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionDescriptorCompose'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter(name="permissionDescriptors")
    def permission_descriptors(self) -> Optional[Sequence[_builtins.str]]:
        """
        References to other descriptors to include in the tree
        """
        return pulumi.get(self, "permission_descriptors")


@pulumi.output_type
class PermissionDescriptorCondition(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "subNode":
            suggest = "sub_node"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PermissionDescriptorCondition. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PermissionDescriptorCondition.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PermissionDescriptorCondition.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 type__: _builtins.str,
                 condition: Optional[Any] = None,
                 sub_node: Optional[Any] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionDescriptorCondition'.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionNot', 'PermissionExpressionOr'] condition: The boolean condition to evaluate.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        :param Union['PermissionDescriptorAllow', 'PermissionDescriptorCompose', 'PermissionDescriptorCondition', 'PermissionDescriptorGroup', 'PermissionDescriptorIfThenElse', 'PermissionDescriptorSelect'] sub_node: The permission descriptor to apply when the condition is true.
               
               Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        """
        pulumi.set(__self__, "type__", 'PermissionDescriptorCondition')
        if condition is not None:
            pulumi.set(__self__, "condition", condition)
        if sub_node is not None:
            pulumi.set(__self__, "sub_node", sub_node)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionDescriptorCondition'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def condition(self) -> Optional[Any]:
        """
        The boolean condition to evaluate.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        return pulumi.get(self, "condition")

    @_builtins.property
    @pulumi.getter(name="subNode")
    def sub_node(self) -> Optional[Any]:
        """
        The permission descriptor to apply when the condition is true.

        Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        """
        return pulumi.get(self, "sub_node")


@pulumi.output_type
class PermissionDescriptorGroup(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 entries: Optional[Sequence[Any]] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionDescriptorGroup'.
        :param Sequence[Union['PermissionDescriptorAllow', 'PermissionDescriptorCompose', 'PermissionDescriptorCondition', 'PermissionDescriptorGroup', 'PermissionDescriptorIfThenElse', 'PermissionDescriptorSelect']] entries: The list of permission descriptor entries in this group.
               
               Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        """
        pulumi.set(__self__, "type__", 'PermissionDescriptorGroup')
        if entries is not None:
            pulumi.set(__self__, "entries", entries)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionDescriptorGroup'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def entries(self) -> Optional[Sequence[Any]]:
        """
        The list of permission descriptor entries in this group.

        Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        """
        return pulumi.get(self, "entries")


@pulumi.output_type
class PermissionDescriptorIfThenElse(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "subNodeForFalse":
            suggest = "sub_node_for_false"
        elif key == "subNodeForTrue":
            suggest = "sub_node_for_true"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PermissionDescriptorIfThenElse. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PermissionDescriptorIfThenElse.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PermissionDescriptorIfThenElse.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 type__: _builtins.str,
                 condition: Optional[Any] = None,
                 sub_node_for_false: Optional[Any] = None,
                 sub_node_for_true: Optional[Any] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionDescriptorIfThenElse'.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionNot', 'PermissionExpressionOr'] condition: The boolean condition to evaluate.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        :param Union['PermissionDescriptorAllow', 'PermissionDescriptorCompose', 'PermissionDescriptorCondition', 'PermissionDescriptorGroup', 'PermissionDescriptorIfThenElse', 'PermissionDescriptorSelect'] sub_node_for_false: The permission descriptor to apply when the condition is false.
               
               Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        :param Union['PermissionDescriptorAllow', 'PermissionDescriptorCompose', 'PermissionDescriptorCondition', 'PermissionDescriptorGroup', 'PermissionDescriptorIfThenElse', 'PermissionDescriptorSelect'] sub_node_for_true: The permission descriptor to apply when the condition is true.
               
               Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        """
        pulumi.set(__self__, "type__", 'PermissionDescriptorIfThenElse')
        if condition is not None:
            pulumi.set(__self__, "condition", condition)
        if sub_node_for_false is not None:
            pulumi.set(__self__, "sub_node_for_false", sub_node_for_false)
        if sub_node_for_true is not None:
            pulumi.set(__self__, "sub_node_for_true", sub_node_for_true)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionDescriptorIfThenElse'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def condition(self) -> Optional[Any]:
        """
        The boolean condition to evaluate.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        return pulumi.get(self, "condition")

    @_builtins.property
    @pulumi.getter(name="subNodeForFalse")
    def sub_node_for_false(self) -> Optional[Any]:
        """
        The permission descriptor to apply when the condition is false.

        Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        """
        return pulumi.get(self, "sub_node_for_false")

    @_builtins.property
    @pulumi.getter(name="subNodeForTrue")
    def sub_node_for_true(self) -> Optional[Any]:
        """
        The permission descriptor to apply when the condition is true.

        Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        """
        return pulumi.get(self, "sub_node_for_true")


@pulumi.output_type
class PermissionDescriptorSelect(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 options: Optional[Sequence['outputs.PermissionSelectvalue']] = None,
                 selector: Optional[Any] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionDescriptorSelect'.
        :param Sequence['PermissionSelectvalue'] options: The available options to select from based on the selector expression.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEnvironment', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionInsightsAccount', 'PermissionExpressionNot', 'PermissionExpressionOr', 'PermissionExpressionStack', 'PermissionExpressionTag', 'PermissionExpressionTeam', 'PermissionLiteralExpressionBool', 'PermissionLiteralExpressionEnvironment', 'PermissionLiteralExpressionInsightsAccount', 'PermissionLiteralExpressionNumber', 'PermissionLiteralExpressionStack', 'PermissionLiteralExpressionString', 'PermissionLiteralExpressionTeam'] selector: The expression used to select which option to apply.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
        """
        pulumi.set(__self__, "type__", 'PermissionDescriptorSelect')
        if options is not None:
            pulumi.set(__self__, "options", options)
        if selector is not None:
            pulumi.set(__self__, "selector", selector)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionDescriptorSelect'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def options(self) -> Optional[Sequence['outputs.PermissionSelectvalue']]:
        """
        The available options to select from based on the selector expression.
        """
        return pulumi.get(self, "options")

    @_builtins.property
    @pulumi.getter
    def selector(self) -> Optional[Any]:
        """
        The expression used to select which option to apply.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
        """
        return pulumi.get(self, "selector")


@pulumi.output_type
class PermissionExpressionAnd(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 left: Optional[Any] = None,
                 right: Optional[Any] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionAnd'.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionNot', 'PermissionExpressionOr'] left: The left operand of the binary boolean expression.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionNot', 'PermissionExpressionOr'] right: The right operand of the binary boolean expression.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionAnd')
        if left is not None:
            pulumi.set(__self__, "left", left)
        if right is not None:
            pulumi.set(__self__, "right", right)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionAnd'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def left(self) -> Optional[Any]:
        """
        The left operand of the binary boolean expression.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        return pulumi.get(self, "left")

    @_builtins.property
    @pulumi.getter
    def right(self) -> Optional[Any]:
        """
        The right operand of the binary boolean expression.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        return pulumi.get(self, "right")


@pulumi.output_type
class PermissionExpressionEnvironment(dict):
    def __init__(__self__, *,
                 type__: _builtins.str):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionEnvironment'.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionEnvironment')

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionEnvironment'.
        """
        return pulumi.get(self, "type__")


@pulumi.output_type
class PermissionExpressionEqual(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 left: Optional[Any] = None,
                 right: Optional[Any] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionEqual'.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEnvironment', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionInsightsAccount', 'PermissionExpressionNot', 'PermissionExpressionOr', 'PermissionExpressionStack', 'PermissionExpressionTag', 'PermissionExpressionTeam', 'PermissionLiteralExpressionBool', 'PermissionLiteralExpressionEnvironment', 'PermissionLiteralExpressionInsightsAccount', 'PermissionLiteralExpressionNumber', 'PermissionLiteralExpressionStack', 'PermissionLiteralExpressionString', 'PermissionLiteralExpressionTeam'] left: The left operand of the equality comparison.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEnvironment', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionInsightsAccount', 'PermissionExpressionNot', 'PermissionExpressionOr', 'PermissionExpressionStack', 'PermissionExpressionTag', 'PermissionExpressionTeam', 'PermissionLiteralExpressionBool', 'PermissionLiteralExpressionEnvironment', 'PermissionLiteralExpressionInsightsAccount', 'PermissionLiteralExpressionNumber', 'PermissionLiteralExpressionStack', 'PermissionLiteralExpressionString', 'PermissionLiteralExpressionTeam'] right: The right operand of the equality comparison.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionEqual')
        if left is not None:
            pulumi.set(__self__, "left", left)
        if right is not None:
            pulumi.set(__self__, "right", right)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionEqual'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def left(self) -> Optional[Any]:
        """
        The left operand of the equality comparison.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
        """
        return pulumi.get(self, "left")

    @_builtins.property
    @pulumi.getter
    def right(self) -> Optional[Any]:
        """
        The right operand of the equality comparison.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
        """
        return pulumi.get(self, "right")


@pulumi.output_type
class PermissionExpressionHasTag(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 context: Optional[Any] = None,
                 key: Optional[_builtins.str] = None,
                 node: Optional[Any] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionHasTag'.
        :param Union['PermissionExpressionEnvironment', 'PermissionExpressionInsightsAccount', 'PermissionExpressionStack', 'PermissionExpressionTeam'] context: The context expression to check for the tag.
               
               Valid `type__` values: PermissionExpressionEnvironment, PermissionExpressionInsightsAccount, PermissionExpressionStack, PermissionExpressionTeam.
        :param _builtins.str key: The tag key to check for.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionNot', 'PermissionExpressionOr'] node: The operand of the unary boolean expression.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionHasTag')
        if context is not None:
            pulumi.set(__self__, "context", context)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if node is not None:
            pulumi.set(__self__, "node", node)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionHasTag'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def context(self) -> Optional[Any]:
        """
        The context expression to check for the tag.

        Valid `type__` values: PermissionExpressionEnvironment, PermissionExpressionInsightsAccount, PermissionExpressionStack, PermissionExpressionTeam.
        """
        return pulumi.get(self, "context")

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[_builtins.str]:
        """
        The tag key to check for.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def node(self) -> Optional[Any]:
        """
        The operand of the unary boolean expression.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        return pulumi.get(self, "node")


@pulumi.output_type
class PermissionExpressionInsightsAccount(dict):
    def __init__(__self__, *,
                 type__: _builtins.str):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionInsightsAccount'.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionInsightsAccount')

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionInsightsAccount'.
        """
        return pulumi.get(self, "type__")


@pulumi.output_type
class PermissionExpressionNot(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 node: Optional[Any] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionNot'.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionNot', 'PermissionExpressionOr'] node: The operand of the unary boolean expression.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionNot')
        if node is not None:
            pulumi.set(__self__, "node", node)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionNot'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def node(self) -> Optional[Any]:
        """
        The operand of the unary boolean expression.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        return pulumi.get(self, "node")


@pulumi.output_type
class PermissionExpressionOr(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 left: Optional[Any] = None,
                 right: Optional[Any] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionOr'.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionNot', 'PermissionExpressionOr'] left: The left operand of the binary boolean expression.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionNot', 'PermissionExpressionOr'] right: The right operand of the binary boolean expression.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionOr')
        if left is not None:
            pulumi.set(__self__, "left", left)
        if right is not None:
            pulumi.set(__self__, "right", right)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionOr'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def left(self) -> Optional[Any]:
        """
        The left operand of the binary boolean expression.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        return pulumi.get(self, "left")

    @_builtins.property
    @pulumi.getter
    def right(self) -> Optional[Any]:
        """
        The right operand of the binary boolean expression.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionNot, PermissionExpressionOr.
        """
        return pulumi.get(self, "right")


@pulumi.output_type
class PermissionExpressionStack(dict):
    def __init__(__self__, *,
                 type__: _builtins.str):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionStack'.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionStack')

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionStack'.
        """
        return pulumi.get(self, "type__")


@pulumi.output_type
class PermissionExpressionTag(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 context: Optional[Any] = None,
                 key: Optional[_builtins.str] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionTag'.
        :param Union['PermissionExpressionEnvironment', 'PermissionExpressionInsightsAccount', 'PermissionExpressionStack', 'PermissionExpressionTeam'] context: The context expression identifying the resource to look up the tag on.
               
               Valid `type__` values: PermissionExpressionEnvironment, PermissionExpressionInsightsAccount, PermissionExpressionStack, PermissionExpressionTeam.
        :param _builtins.str key: The tag key to retrieve.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionTag')
        if context is not None:
            pulumi.set(__self__, "context", context)
        if key is not None:
            pulumi.set(__self__, "key", key)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionTag'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def context(self) -> Optional[Any]:
        """
        The context expression identifying the resource to look up the tag on.

        Valid `type__` values: PermissionExpressionEnvironment, PermissionExpressionInsightsAccount, PermissionExpressionStack, PermissionExpressionTeam.
        """
        return pulumi.get(self, "context")

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[_builtins.str]:
        """
        The tag key to retrieve.
        """
        return pulumi.get(self, "key")


@pulumi.output_type
class PermissionExpressionTeam(dict):
    def __init__(__self__, *,
                 type__: _builtins.str):
        """
        :param _builtins.str type__: Expected value is 'PermissionExpressionTeam'.
        """
        pulumi.set(__self__, "type__", 'PermissionExpressionTeam')

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionExpressionTeam'.
        """
        return pulumi.get(self, "type__")


@pulumi.output_type
class PermissionLiteralExpressionBool(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 value: Optional[_builtins.bool] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionLiteralExpressionBool'.
        :param _builtins.bool value: The boolean literal value.
        """
        pulumi.set(__self__, "type__", 'PermissionLiteralExpressionBool')
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionLiteralExpressionBool'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.bool]:
        """
        The boolean literal value.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class PermissionLiteralExpressionEnvironment(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 identity: Optional[_builtins.str] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionLiteralExpressionEnvironment'.
        :param _builtins.str identity: The identity of the environment.
        """
        pulumi.set(__self__, "type__", 'PermissionLiteralExpressionEnvironment')
        if identity is not None:
            pulumi.set(__self__, "identity", identity)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionLiteralExpressionEnvironment'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def identity(self) -> Optional[_builtins.str]:
        """
        The identity of the environment.
        """
        return pulumi.get(self, "identity")


@pulumi.output_type
class PermissionLiteralExpressionInsightsAccount(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 identity: Optional[_builtins.str] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionLiteralExpressionInsightsAccount'.
        :param _builtins.str identity: The identity of the Insights account.
        """
        pulumi.set(__self__, "type__", 'PermissionLiteralExpressionInsightsAccount')
        if identity is not None:
            pulumi.set(__self__, "identity", identity)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionLiteralExpressionInsightsAccount'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def identity(self) -> Optional[_builtins.str]:
        """
        The identity of the Insights account.
        """
        return pulumi.get(self, "identity")


@pulumi.output_type
class PermissionLiteralExpressionNumber(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 value: Optional[_builtins.float] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionLiteralExpressionNumber'.
        :param _builtins.float value: The numeric literal value.
        """
        pulumi.set(__self__, "type__", 'PermissionLiteralExpressionNumber')
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionLiteralExpressionNumber'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.float]:
        """
        The numeric literal value.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class PermissionLiteralExpressionStack(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 identity: Optional[_builtins.str] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionLiteralExpressionStack'.
        :param _builtins.str identity: The identity of the stack.
        """
        pulumi.set(__self__, "type__", 'PermissionLiteralExpressionStack')
        if identity is not None:
            pulumi.set(__self__, "identity", identity)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionLiteralExpressionStack'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def identity(self) -> Optional[_builtins.str]:
        """
        The identity of the stack.
        """
        return pulumi.get(self, "identity")


@pulumi.output_type
class PermissionLiteralExpressionString(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionLiteralExpressionString'.
        :param _builtins.str value: The string literal value.
        """
        pulumi.set(__self__, "type__", 'PermissionLiteralExpressionString')
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionLiteralExpressionString'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        The string literal value.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class PermissionLiteralExpressionTeam(dict):
    def __init__(__self__, *,
                 type__: _builtins.str,
                 identity: Optional[_builtins.str] = None):
        """
        :param _builtins.str type__: Expected value is 'PermissionLiteralExpressionTeam'.
        :param _builtins.str identity: The identity of the team.
        """
        pulumi.set(__self__, "type__", 'PermissionLiteralExpressionTeam')
        if identity is not None:
            pulumi.set(__self__, "identity", identity)

    @_builtins.property
    @pulumi.getter
    def type__(self) -> _builtins.str:
        """
        Expected value is 'PermissionLiteralExpressionTeam'.
        """
        return pulumi.get(self, "type__")

    @_builtins.property
    @pulumi.getter
    def identity(self) -> Optional[_builtins.str]:
        """
        The identity of the team.
        """
        return pulumi.get(self, "identity")


@pulumi.output_type
class PermissionSelectvalue(dict):
    """
    PermissionSelectvalue pairs a value expression with its corresponding permission descriptor node.
    """
    def __init__(__self__, *,
                 node: Optional[Any] = None,
                 value: Optional[Any] = None):
        """
        PermissionSelectvalue pairs a value expression with its corresponding permission descriptor node.

        :param Union['PermissionDescriptorAllow', 'PermissionDescriptorCompose', 'PermissionDescriptorCondition', 'PermissionDescriptorGroup', 'PermissionDescriptorIfThenElse', 'PermissionDescriptorSelect'] node: The permission descriptor to apply when this value matches.
               
               Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        :param Union['PermissionExpressionAnd', 'PermissionExpressionEnvironment', 'PermissionExpressionEqual', 'PermissionExpressionHasTag', 'PermissionExpressionInsightsAccount', 'PermissionExpressionNot', 'PermissionExpressionOr', 'PermissionExpressionStack', 'PermissionExpressionTag', 'PermissionExpressionTeam', 'PermissionLiteralExpressionBool', 'PermissionLiteralExpressionEnvironment', 'PermissionLiteralExpressionInsightsAccount', 'PermissionLiteralExpressionNumber', 'PermissionLiteralExpressionStack', 'PermissionLiteralExpressionString', 'PermissionLiteralExpressionTeam'] value: The value expression to match against the selector.
               
               Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
        """
        if node is not None:
            pulumi.set(__self__, "node", node)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def node(self) -> Optional[Any]:
        """
        The permission descriptor to apply when this value matches.

        Valid `type__` values: PermissionDescriptorAllow, PermissionDescriptorCompose, PermissionDescriptorCondition, PermissionDescriptorGroup, PermissionDescriptorIfThenElse, PermissionDescriptorSelect.
        """
        return pulumi.get(self, "node")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[Any]:
        """
        The value expression to match against the selector.

        Valid `type__` values: PermissionExpressionAnd, PermissionExpressionEnvironment, PermissionExpressionEqual, PermissionExpressionHasTag, PermissionExpressionInsightsAccount, PermissionExpressionNot, PermissionExpressionOr, PermissionExpressionStack, PermissionExpressionTag, PermissionExpressionTeam, PermissionLiteralExpressionBool, PermissionLiteralExpressionEnvironment, PermissionLiteralExpressionInsightsAccount, PermissionLiteralExpressionNumber, PermissionLiteralExpressionStack, PermissionLiteralExpressionString, PermissionLiteralExpressionTeam.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class RbacPermissionConstraints(dict):
    """
    Constraints that can be applied to an RBAC permission.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "MaxOpenDuration":
            suggest = "max_open_duration"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RbacPermissionConstraints. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RbacPermissionConstraints.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RbacPermissionConstraints.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 max_open_duration: Optional[_builtins.int] = None):
        """
        Constraints that can be applied to an RBAC permission.

        :param _builtins.int max_open_duration: If not zero, the amount of time, in seconds, to keep an environment open
        """
        if max_open_duration is not None:
            pulumi.set(__self__, "max_open_duration", max_open_duration)

    @_builtins.property
    @pulumi.getter(name="MaxOpenDuration")
    def max_open_duration(self) -> Optional[_builtins.int]:
        """
        If not zero, the amount of time, in seconds, to keep an environment open
        """
        return pulumi.get(self, "max_open_duration")


@pulumi.output_type
class ScanStatus(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "finishedAt":
            suggest = "finished_at"
        elif key == "jobTimeout":
            suggest = "job_timeout"
        elif key == "lastUpdatedAt":
            suggest = "last_updated_at"
        elif key == "orgId":
            suggest = "org_id"
        elif key == "startedAt":
            suggest = "started_at"
        elif key == "userId":
            suggest = "user_id"
        elif key == "accountName":
            suggest = "account_name"
        elif key == "resourceCount":
            suggest = "resource_count"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ScanStatus. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ScanStatus.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ScanStatus.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 finished_at: _builtins.str,
                 id: _builtins.str,
                 job_timeout: _builtins.str,
                 last_updated_at: _builtins.str,
                 org_id: _builtins.str,
                 started_at: _builtins.str,
                 status: _builtins.str,
                 user_id: _builtins.str,
                 account_name: Optional[_builtins.str] = None,
                 jobs: Optional[Sequence['outputs.JobRun']] = None,
                 resource_count: Optional[_builtins.int] = None):
        """
        :param _builtins.str finished_at: The time the workflow run finished, if completed.
        :param _builtins.str id: The unique identifier of the workflow run.
        :param _builtins.str job_timeout: The timeout for jobs in the workflow run.
        :param _builtins.str last_updated_at: The time the workflow run was last updated.
        :param _builtins.str org_id: The organization ID.
        :param _builtins.str started_at: The time the workflow run started.
        :param _builtins.str status: The current status of the workflow run.
        :param _builtins.str user_id: The user ID who initiated the workflow run.
        :param _builtins.str account_name: The name of the insights account associated with this scan.
        :param Sequence['JobRun'] jobs: The list of job runs within the workflow.
        :param _builtins.int resource_count: The number of resources discovered by this scan.
        """
        pulumi.set(__self__, "finished_at", finished_at)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "job_timeout", job_timeout)
        pulumi.set(__self__, "last_updated_at", last_updated_at)
        pulumi.set(__self__, "org_id", org_id)
        pulumi.set(__self__, "started_at", started_at)
        pulumi.set(__self__, "status", status)
        pulumi.set(__self__, "user_id", user_id)
        if account_name is not None:
            pulumi.set(__self__, "account_name", account_name)
        if jobs is not None:
            pulumi.set(__self__, "jobs", jobs)
        if resource_count is not None:
            pulumi.set(__self__, "resource_count", resource_count)

    @_builtins.property
    @pulumi.getter(name="finishedAt")
    def finished_at(self) -> _builtins.str:
        """
        The time the workflow run finished, if completed.
        """
        return pulumi.get(self, "finished_at")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the workflow run.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="jobTimeout")
    def job_timeout(self) -> _builtins.str:
        """
        The timeout for jobs in the workflow run.
        """
        return pulumi.get(self, "job_timeout")

    @_builtins.property
    @pulumi.getter(name="lastUpdatedAt")
    def last_updated_at(self) -> _builtins.str:
        """
        The time the workflow run was last updated.
        """
        return pulumi.get(self, "last_updated_at")

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> _builtins.str:
        """
        The organization ID.
        """
        return pulumi.get(self, "org_id")

    @_builtins.property
    @pulumi.getter(name="startedAt")
    def started_at(self) -> _builtins.str:
        """
        The time the workflow run started.
        """
        return pulumi.get(self, "started_at")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        The current status of the workflow run.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> _builtins.str:
        """
        The user ID who initiated the workflow run.
        """
        return pulumi.get(self, "user_id")

    @_builtins.property
    @pulumi.getter(name="accountName")
    def account_name(self) -> Optional[_builtins.str]:
        """
        The name of the insights account associated with this scan.
        """
        return pulumi.get(self, "account_name")

    @_builtins.property
    @pulumi.getter
    def jobs(self) -> Optional[Sequence['outputs.JobRun']]:
        """
        The list of job runs within the workflow.
        """
        return pulumi.get(self, "jobs")

    @_builtins.property
    @pulumi.getter(name="resourceCount")
    def resource_count(self) -> Optional[_builtins.int]:
        """
        The number of resources discovered by this scan.
        """
        return pulumi.get(self, "resource_count")


@pulumi.output_type
class StepRun(dict):
    """
    StepRun contains information about a step run.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "lastUpdated":
            suggest = "last_updated"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in StepRun. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        StepRun.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        StepRun.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 name: _builtins.str,
                 status: _builtins.str,
                 last_updated: Optional[_builtins.str] = None,
                 started: Optional[_builtins.str] = None):
        """
        StepRun contains information about a step run.

        :param _builtins.str name: The name of the step.
        :param _builtins.str status: The current status of the step.
        :param _builtins.str last_updated: The timestamp when the step was last updated.
        :param _builtins.str started: The timestamp when the step started.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "status", status)
        if last_updated is not None:
            pulumi.set(__self__, "last_updated", last_updated)
        if started is not None:
            pulumi.set(__self__, "started", started)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the step.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        The current status of the step.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> Optional[_builtins.str]:
        """
        The timestamp when the step was last updated.
        """
        return pulumi.get(self, "last_updated")

    @_builtins.property
    @pulumi.getter
    def started(self) -> Optional[_builtins.str]:
        """
        The timestamp when the step started.
        """
        return pulumi.get(self, "started")


@pulumi.output_type
class TargetEntityEnvironment(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "entityType":
            suggest = "entity_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in TargetEntityEnvironment. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        TargetEntityEnvironment.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        TargetEntityEnvironment.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 entity_type: _builtins.str,
                 name: _builtins.str,
                 project: _builtins.str):
        """
        :param _builtins.str entity_type: Expected value is 'environment'.
        :param _builtins.str name: The environment name
        :param _builtins.str project: The project name
        """
        pulumi.set(__self__, "entity_type", 'environment')
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "project", project)

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> _builtins.str:
        """
        Expected value is 'environment'.
        """
        return pulumi.get(self, "entity_type")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The environment name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def project(self) -> _builtins.str:
        """
        The project name
        """
        return pulumi.get(self, "project")


@pulumi.output_type
class TemplateDestination(dict):
    """
    TemplateDestination describes the destination for a template.
    """
    def __init__(__self__, *,
                 url: _builtins.str):
        """
        TemplateDestination describes the destination for a template.

        :param _builtins.str url: The destination URL.
        """
        pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def url(self) -> _builtins.str:
        """
        The destination URL.
        """
        return pulumi.get(self, "url")


@pulumi.output_type
class UserInfo(dict):
    """
    UserInfo contains just the display information for a user.  This information may be returned from public APIs,
    and as such this structure must not contain sensitive information.  Please refer to User for this sort of thing.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "avatarUrl":
            suggest = "avatar_url"
        elif key == "githubLogin":
            suggest = "github_login"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in UserInfo. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        UserInfo.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        UserInfo.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 avatar_url: _builtins.str,
                 github_login: _builtins.str,
                 name: _builtins.str,
                 email: Optional[_builtins.str] = None):
        """
        UserInfo contains just the display information for a user.  This information may be returned from public APIs,
        and as such this structure must not contain sensitive information.  Please refer to User for this sort of thing.

        :param _builtins.str avatar_url: The URL of the user's avatar image.
        :param _builtins.str github_login: The user's login name.
        :param _builtins.str name: The user's display name.
        :param _builtins.str email: The user's email address. It is only populated on selected endpoints and is
               omitted from most responses. Treat it as sensitive information.
        """
        pulumi.set(__self__, "avatar_url", avatar_url)
        pulumi.set(__self__, "github_login", github_login)
        pulumi.set(__self__, "name", name)
        if email is not None:
            pulumi.set(__self__, "email", email)

    @_builtins.property
    @pulumi.getter(name="avatarUrl")
    def avatar_url(self) -> _builtins.str:
        """
        The URL of the user's avatar image.
        """
        return pulumi.get(self, "avatar_url")

    @_builtins.property
    @pulumi.getter(name="githubLogin")
    def github_login(self) -> _builtins.str:
        """
        The user's login name.
        """
        return pulumi.get(self, "github_login")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The user's display name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def email(self) -> Optional[_builtins.str]:
        """
        The user's email address. It is only populated on selected endpoints and is
        omitted from most responses. Treat it as sensitive information.
        """
        return pulumi.get(self, "email")


