// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package esc

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-pulumiservice/sdk/go/pulumiservice/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Adds a new user-defined tag to a Pulumi ESC environment. Tags are key-value pairs that provide contextual metadata for organizing and searching environments (e.g., region=us-east-1, team=platform). The tag name and value are provided in the request body. Returns the created EnvironmentTag on success. Returns 409 if a tag with the same name already exists on the environment.
type EnvironmentTag struct {
	pulumi.CustomResourceState

	// The timestamp when the tag was created.
	Created pulumi.StringOutput `pulumi:"created"`
	// The login name of the user who last edited the tag.
	EditorLogin pulumi.StringOutput `pulumi:"editorLogin"`
	// The display name of the user who last edited the tag.
	EditorName pulumi.StringOutput `pulumi:"editorName"`
	// The environment name
	EnvName pulumi.StringOutput `pulumi:"envName"`
	// The timestamp when the tag was last modified.
	Modified pulumi.StringOutput `pulumi:"modified"`
	// The name of the tag.
	Name pulumi.StringOutput `pulumi:"name"`
	// The organization name
	OrgName pulumi.StringOutput `pulumi:"orgName"`
	// The project name
	ProjectName pulumi.StringOutput `pulumi:"projectName"`
	// The value of the tag.
	Value pulumi.StringOutput `pulumi:"value"`
}

// NewEnvironmentTag registers a new resource with the given unique name, arguments, and options.
func NewEnvironmentTag(ctx *pulumi.Context,
	name string, args *EnvironmentTagArgs, opts ...pulumi.ResourceOption) (*EnvironmentTag, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EnvName == nil {
		return nil, errors.New("invalid value for required argument 'EnvName'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.OrgName == nil {
		return nil, errors.New("invalid value for required argument 'OrgName'")
	}
	if args.ProjectName == nil {
		return nil, errors.New("invalid value for required argument 'ProjectName'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"envName",
		"orgName",
		"projectName",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EnvironmentTag
	err := ctx.RegisterResource("pulumiservice:v2/esc:EnvironmentTag", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnvironmentTag gets an existing EnvironmentTag resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnvironmentTag(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EnvironmentTagState, opts ...pulumi.ResourceOption) (*EnvironmentTag, error) {
	var resource EnvironmentTag
	err := ctx.ReadResource("pulumiservice:v2/esc:EnvironmentTag", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EnvironmentTag resources.
type environmentTagState struct {
}

type EnvironmentTagState struct {
}

func (EnvironmentTagState) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentTagState)(nil)).Elem()
}

type environmentTagArgs struct {
	// The environment name
	EnvName string `pulumi:"envName"`
	// The name
	Name string `pulumi:"name"`
	// The organization name
	OrgName string `pulumi:"orgName"`
	// The project name
	ProjectName string `pulumi:"projectName"`
	// The value
	Value string `pulumi:"value"`
}

// The set of arguments for constructing a EnvironmentTag resource.
type EnvironmentTagArgs struct {
	// The environment name
	EnvName pulumi.StringInput
	// The name
	Name pulumi.StringInput
	// The organization name
	OrgName pulumi.StringInput
	// The project name
	ProjectName pulumi.StringInput
	// The value
	Value pulumi.StringInput
}

func (EnvironmentTagArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentTagArgs)(nil)).Elem()
}

type EnvironmentTagInput interface {
	pulumi.Input

	ToEnvironmentTagOutput() EnvironmentTagOutput
	ToEnvironmentTagOutputWithContext(ctx context.Context) EnvironmentTagOutput
}

func (*EnvironmentTag) ElementType() reflect.Type {
	return reflect.TypeOf((**EnvironmentTag)(nil)).Elem()
}

func (i *EnvironmentTag) ToEnvironmentTagOutput() EnvironmentTagOutput {
	return i.ToEnvironmentTagOutputWithContext(context.Background())
}

func (i *EnvironmentTag) ToEnvironmentTagOutputWithContext(ctx context.Context) EnvironmentTagOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentTagOutput)
}

// EnvironmentTagArrayInput is an input type that accepts EnvironmentTagArray and EnvironmentTagArrayOutput values.
// You can construct a concrete instance of `EnvironmentTagArrayInput` via:
//
//	EnvironmentTagArray{ EnvironmentTagArgs{...} }
type EnvironmentTagArrayInput interface {
	pulumi.Input

	ToEnvironmentTagArrayOutput() EnvironmentTagArrayOutput
	ToEnvironmentTagArrayOutputWithContext(context.Context) EnvironmentTagArrayOutput
}

type EnvironmentTagArray []EnvironmentTagInput

func (EnvironmentTagArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EnvironmentTag)(nil)).Elem()
}

func (i EnvironmentTagArray) ToEnvironmentTagArrayOutput() EnvironmentTagArrayOutput {
	return i.ToEnvironmentTagArrayOutputWithContext(context.Background())
}

func (i EnvironmentTagArray) ToEnvironmentTagArrayOutputWithContext(ctx context.Context) EnvironmentTagArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentTagArrayOutput)
}

// EnvironmentTagMapInput is an input type that accepts EnvironmentTagMap and EnvironmentTagMapOutput values.
// You can construct a concrete instance of `EnvironmentTagMapInput` via:
//
//	EnvironmentTagMap{ "key": EnvironmentTagArgs{...} }
type EnvironmentTagMapInput interface {
	pulumi.Input

	ToEnvironmentTagMapOutput() EnvironmentTagMapOutput
	ToEnvironmentTagMapOutputWithContext(context.Context) EnvironmentTagMapOutput
}

type EnvironmentTagMap map[string]EnvironmentTagInput

func (EnvironmentTagMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EnvironmentTag)(nil)).Elem()
}

func (i EnvironmentTagMap) ToEnvironmentTagMapOutput() EnvironmentTagMapOutput {
	return i.ToEnvironmentTagMapOutputWithContext(context.Background())
}

func (i EnvironmentTagMap) ToEnvironmentTagMapOutputWithContext(ctx context.Context) EnvironmentTagMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentTagMapOutput)
}

type EnvironmentTagOutput struct{ *pulumi.OutputState }

func (EnvironmentTagOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EnvironmentTag)(nil)).Elem()
}

func (o EnvironmentTagOutput) ToEnvironmentTagOutput() EnvironmentTagOutput {
	return o
}

func (o EnvironmentTagOutput) ToEnvironmentTagOutputWithContext(ctx context.Context) EnvironmentTagOutput {
	return o
}

// The timestamp when the tag was created.
func (o EnvironmentTagOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.Created }).(pulumi.StringOutput)
}

// The login name of the user who last edited the tag.
func (o EnvironmentTagOutput) EditorLogin() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.EditorLogin }).(pulumi.StringOutput)
}

// The display name of the user who last edited the tag.
func (o EnvironmentTagOutput) EditorName() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.EditorName }).(pulumi.StringOutput)
}

// The environment name
func (o EnvironmentTagOutput) EnvName() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.EnvName }).(pulumi.StringOutput)
}

// The timestamp when the tag was last modified.
func (o EnvironmentTagOutput) Modified() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.Modified }).(pulumi.StringOutput)
}

// The name of the tag.
func (o EnvironmentTagOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The organization name
func (o EnvironmentTagOutput) OrgName() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.OrgName }).(pulumi.StringOutput)
}

// The project name
func (o EnvironmentTagOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.ProjectName }).(pulumi.StringOutput)
}

// The value of the tag.
func (o EnvironmentTagOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentTag) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

type EnvironmentTagArrayOutput struct{ *pulumi.OutputState }

func (EnvironmentTagArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EnvironmentTag)(nil)).Elem()
}

func (o EnvironmentTagArrayOutput) ToEnvironmentTagArrayOutput() EnvironmentTagArrayOutput {
	return o
}

func (o EnvironmentTagArrayOutput) ToEnvironmentTagArrayOutputWithContext(ctx context.Context) EnvironmentTagArrayOutput {
	return o
}

func (o EnvironmentTagArrayOutput) Index(i pulumi.IntInput) EnvironmentTagOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EnvironmentTag {
		return vs[0].([]*EnvironmentTag)[vs[1].(int)]
	}).(EnvironmentTagOutput)
}

type EnvironmentTagMapOutput struct{ *pulumi.OutputState }

func (EnvironmentTagMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EnvironmentTag)(nil)).Elem()
}

func (o EnvironmentTagMapOutput) ToEnvironmentTagMapOutput() EnvironmentTagMapOutput {
	return o
}

func (o EnvironmentTagMapOutput) ToEnvironmentTagMapOutputWithContext(ctx context.Context) EnvironmentTagMapOutput {
	return o
}

func (o EnvironmentTagMapOutput) MapIndex(k pulumi.StringInput) EnvironmentTagOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EnvironmentTag {
		return vs[0].(map[string]*EnvironmentTag)[vs[1].(string)]
	}).(EnvironmentTagOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentTagInput)(nil)).Elem(), &EnvironmentTag{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentTagArrayInput)(nil)).Elem(), EnvironmentTagArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentTagMapInput)(nil)).Elem(), EnvironmentTagMap{})
	pulumi.RegisterOutputType(EnvironmentTagOutput{})
	pulumi.RegisterOutputType(EnvironmentTagArrayOutput{})
	pulumi.RegisterOutputType(EnvironmentTagMapOutput{})
}
