// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.Api.Deployments.Outputs
{

    /// <summary>
    /// SSHAuth configures ssh-based auth for git authentication.
    /// SSHPrivateKey is required but password is optional.
    /// </summary>
    [OutputType]
    public sealed class SSHAuth
    {
        /// <summary>
        /// An optional password or passphrase for the SSH private key.
        /// </summary>
        public readonly object? Password;
        /// <summary>
        /// The SSH private key used for authentication.
        /// </summary>
        public readonly object SshPrivateKey;

        [OutputConstructor]
        private SSHAuth(
            object? password,

            object sshPrivateKey)
        {
            Password = password;
            SshPrivateKey = sshPrivateKey;
        }
    }
}
