// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.V2.Integrations
{
    /// <summary>
    /// Creates a new custom VCS integration for an organization. Custom VCS integrations allow connecting self-hosted or third-party version control systems (e.g. Gitea, Forgejo, Bitbucket Server) to Pulumi Deployments. Credentials are managed via ESC environments, and deployments are triggered by inbound webhooks. Returns the created integration including its webhook URL and HMAC secret for signature verification.
    /// </summary>
    [PulumiServiceResourceType("pulumiservice:v2/integrations:CustomVCSIntegration")]
    public partial class CustomVCSIntegration : global::Pulumi.CustomResource
    {
        /// <summary>
        /// URL prefix for repositories covered by this integration
        /// </summary>
        [Output("baseUrl")]
        public Output<string> BaseUrl { get; private set; } = null!;

        /// <summary>
        /// ISO 8601 timestamp of when the integration was created
        /// </summary>
        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// ESC environment reference in 'project/envName' format containing VCS credentials
        /// </summary>
        [Output("environment")]
        public Output<string> Environment { get; private set; } = null!;

        /// <summary>
        /// Unique identifier (UUID) for this integration
        /// </summary>
        [Output("integrationId")]
        public Output<string> IntegrationId { get; private set; } = null!;

        /// <summary>
        /// ISO 8601 timestamp of when the integration was last modified
        /// </summary>
        [Output("modified")]
        public Output<string> Modified { get; private set; } = null!;

        /// <summary>
        /// Human-readable name for the integration
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The organization name
        /// </summary>
        [Output("orgName")]
        public Output<string> OrgName { get; private set; } = null!;

        /// <summary>
        /// List of repositories configured on this integration
        /// </summary>
        [Output("repositories")]
        public Output<ImmutableArray<object>> Repositories { get; private set; } = null!;

        /// <summary>
        /// Version control system type
        /// </summary>
        [Output("vcsType")]
        public Output<string> VcsType { get; private set; } = null!;

        /// <summary>
        /// HMAC secret for webhook signature verification. Only returned on integration creation; subsequent GET requests omit this field.
        /// </summary>
        [Output("webhookSecret")]
        public Output<string?> WebhookSecret { get; private set; } = null!;

        /// <summary>
        /// Full webhook endpoint URL that the external VCS should POST events to. This URL is generated by the service and includes the integration ID.
        /// </summary>
        [Output("webhookUrl")]
        public Output<string?> WebhookUrl { get; private set; } = null!;


        /// <summary>
        /// Create a CustomVCSIntegration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CustomVCSIntegration(string name, CustomVCSIntegrationArgs args, CustomResourceOptions? options = null)
            : base("pulumiservice:v2/integrations:CustomVCSIntegration", name, args ?? new CustomVCSIntegrationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CustomVCSIntegration(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pulumiservice:v2/integrations:CustomVCSIntegration", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "webhookSecret",
                },
                ReplaceOnChanges =
                {
                    "orgName",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CustomVCSIntegration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CustomVCSIntegration Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new CustomVCSIntegration(name, id, options);
        }
    }

    public sealed class CustomVCSIntegrationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URL prefix for repositories covered by this integration (e.g. 'https://gitea.example.com/myorg'). Used to match repositories to integrations.
        /// </summary>
        [Input("baseUrl", required: true)]
        public Input<string> BaseUrl { get; set; } = null!;

        /// <summary>
        /// ESC environment reference in 'project/envName' format containing VCS credentials (e.g. SSH keys, access tokens) used for repository operations
        /// </summary>
        [Input("environment", required: true)]
        public Input<string> Environment { get; set; } = null!;

        /// <summary>
        /// The custom VCS integration identifier
        /// </summary>
        [Input("integrationId")]
        public Input<string>? IntegrationId { get; set; }

        /// <summary>
        /// Human-readable name for the integration, unique within the organization (e.g. 'Gitea Production')
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The organization name
        /// </summary>
        [Input("orgName", required: true)]
        public Input<string> OrgName { get; set; } = null!;

        /// <summary>
        /// Version control system type. Defaults to 'git' if not specified.
        /// </summary>
        [Input("vcsType")]
        public Input<string>? VcsType { get; set; }

        public CustomVCSIntegrationArgs()
        {
        }
        public static new CustomVCSIntegrationArgs Empty => new CustomVCSIntegrationArgs();
    }
}
