// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.pulumiservice.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class OrganizationMemberInfo {
    /**
     * @return The member&#39;s email address.
     * 
     */
    private String email;
    /**
     * @return The member&#39;s GitHub login.
     * 
     */
    private String githubLogin;
    /**
     * @return Whether this member has a Pulumi Cloud account.
     * 
     */
    private Boolean knownToPulumi;
    /**
     * @return The member&#39;s display name.
     * 
     */
    private String name;
    /**
     * @return The member&#39;s built-in role (member, admin, billing-manager).
     * 
     */
    private String role;
    /**
     * @return The custom role ID assigned to this member, if any.
     * 
     */
    private @Nullable String roleId;
    /**
     * @return The custom role name assigned to this member, if any.
     * 
     */
    private @Nullable String roleName;
    /**
     * @return The member&#39;s Pulumi Cloud username.
     * 
     */
    private String username;
    /**
     * @return Whether this member is an admin in Pulumi Cloud without admin access on the backing identity provider.
     * 
     */
    private Boolean virtualAdmin;

    private OrganizationMemberInfo() {}
    /**
     * @return The member&#39;s email address.
     * 
     */
    public String email() {
        return this.email;
    }
    /**
     * @return The member&#39;s GitHub login.
     * 
     */
    public String githubLogin() {
        return this.githubLogin;
    }
    /**
     * @return Whether this member has a Pulumi Cloud account.
     * 
     */
    public Boolean knownToPulumi() {
        return this.knownToPulumi;
    }
    /**
     * @return The member&#39;s display name.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The member&#39;s built-in role (member, admin, billing-manager).
     * 
     */
    public String role() {
        return this.role;
    }
    /**
     * @return The custom role ID assigned to this member, if any.
     * 
     */
    public Optional<String> roleId() {
        return Optional.ofNullable(this.roleId);
    }
    /**
     * @return The custom role name assigned to this member, if any.
     * 
     */
    public Optional<String> roleName() {
        return Optional.ofNullable(this.roleName);
    }
    /**
     * @return The member&#39;s Pulumi Cloud username.
     * 
     */
    public String username() {
        return this.username;
    }
    /**
     * @return Whether this member is an admin in Pulumi Cloud without admin access on the backing identity provider.
     * 
     */
    public Boolean virtualAdmin() {
        return this.virtualAdmin;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(OrganizationMemberInfo defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String email;
        private String githubLogin;
        private Boolean knownToPulumi;
        private String name;
        private String role;
        private @Nullable String roleId;
        private @Nullable String roleName;
        private String username;
        private Boolean virtualAdmin;
        public Builder() {}
        public Builder(OrganizationMemberInfo defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.email = defaults.email;
    	      this.githubLogin = defaults.githubLogin;
    	      this.knownToPulumi = defaults.knownToPulumi;
    	      this.name = defaults.name;
    	      this.role = defaults.role;
    	      this.roleId = defaults.roleId;
    	      this.roleName = defaults.roleName;
    	      this.username = defaults.username;
    	      this.virtualAdmin = defaults.virtualAdmin;
        }

        @CustomType.Setter
        public Builder email(String email) {
            if (email == null) {
              throw new MissingRequiredPropertyException("OrganizationMemberInfo", "email");
            }
            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder githubLogin(String githubLogin) {
            if (githubLogin == null) {
              throw new MissingRequiredPropertyException("OrganizationMemberInfo", "githubLogin");
            }
            this.githubLogin = githubLogin;
            return this;
        }
        @CustomType.Setter
        public Builder knownToPulumi(Boolean knownToPulumi) {
            if (knownToPulumi == null) {
              throw new MissingRequiredPropertyException("OrganizationMemberInfo", "knownToPulumi");
            }
            this.knownToPulumi = knownToPulumi;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("OrganizationMemberInfo", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("OrganizationMemberInfo", "role");
            }
            this.role = role;
            return this;
        }
        @CustomType.Setter
        public Builder roleId(@Nullable String roleId) {

            this.roleId = roleId;
            return this;
        }
        @CustomType.Setter
        public Builder roleName(@Nullable String roleName) {

            this.roleName = roleName;
            return this;
        }
        @CustomType.Setter
        public Builder username(String username) {
            if (username == null) {
              throw new MissingRequiredPropertyException("OrganizationMemberInfo", "username");
            }
            this.username = username;
            return this;
        }
        @CustomType.Setter
        public Builder virtualAdmin(Boolean virtualAdmin) {
            if (virtualAdmin == null) {
              throw new MissingRequiredPropertyException("OrganizationMemberInfo", "virtualAdmin");
            }
            this.virtualAdmin = virtualAdmin;
            return this;
        }
        public OrganizationMemberInfo build() {
            final var _resultValue = new OrganizationMemberInfo();
            _resultValue.email = email;
            _resultValue.githubLogin = githubLogin;
            _resultValue.knownToPulumi = knownToPulumi;
            _resultValue.name = name;
            _resultValue.role = role;
            _resultValue.roleId = roleId;
            _resultValue.roleName = roleName;
            _resultValue.username = username;
            _resultValue.virtualAdmin = virtualAdmin;
            return _resultValue;
        }
    }
}
