// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.Inputs
{

    public sealed class PolicyPackPolicyInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("configSchema")]
        private InputMap<object>? _configSchema;

        /// <summary>
        /// JSON Schema (properties/required/type) for the policy's runtime config. Values are supplied per-policy via the PolicyGroup's policyPacks[].config map.
        /// </summary>
        public InputMap<object> ConfigSchema
        {
            get => _configSchema ?? (_configSchema = new InputMap<object>());
            set => _configSchema = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// One of: advisory, mandatory, disabled.
        /// </summary>
        [Input("enforcementLevel")]
        public Input<string>? EnforcementLevel { get; set; }

        [Input("message")]
        public Input<string>? Message { get; set; }

        /// <summary>
        /// Unique policy name within the pack.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public PolicyPackPolicyInputArgs()
        {
        }
        public static new PolicyPackPolicyInputArgs Empty => new PolicyPackPolicyInputArgs();
    }
}
