// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.Inputs
{

    public sealed class RoleTagCondition : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The tag key.
        /// </summary>
        [Input("key", required: true)]
        public string Key { get; set; } = null!;

        /// <summary>
        /// How the tag is compared. Defaults to `equals`.
        /// </summary>
        [Input("operator")]
        public Pulumi.PulumiService.RoleTagOperator? Operator { get; set; }

        /// <summary>
        /// The tag value. When omitted, the condition matches on whether the tag is present.
        /// </summary>
        [Input("value")]
        public string? Value { get; set; }

        public RoleTagCondition()
        {
        }
        public static new RoleTagCondition Empty => new RoleTagCondition();
    }
}
