// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.PulumiService.Api.Agents.Inputs
{

    public sealed class AgentEntityPRArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If the PR has been merged already
        /// </summary>
        [Input("merged", required: true)]
        public Input<bool> Merged { get; set; } = null!;

        /// <summary>
        /// The PR number
        /// </summary>
        [Input("number", required: true)]
        public Input<int> Number { get; set; } = null!;

        /// <summary>
        /// The repo the PR is in
        /// </summary>
        [Input("repo", required: true)]
        public Input<Inputs.AgentEntityRepositoryArgs> Repo { get; set; } = null!;

        /// <summary>
        /// Expected value is 'pull_request'.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public AgentEntityPRArgs()
        {
        }
        public static new AgentEntityPRArgs Empty => new AgentEntityPRArgs();
    }
}
